import { authorizeBoardRead, authorizeWrite, body, json, requireDb, type Env } from './_lib';
const views = new Set(['summary','assets','depreciation']);
export const onRequestGet: PagesFunction<Env> = async ({ env, request }) => {
  const u = new URL(request.url); const boardId = (u.searchParams.get('boardId') || '').trim(); const view = u.searchParams.get('view') || 'summary';
  if (!boardId) return json({ error: 'boardId_required' }, { status: 400 }); if (!views.has(view)) return json({ error: 'unknown_view', allowed: [...views] }, { status: 400 }); if (!(await authorizeBoardRead(request, env, boardId))) return json({ error: 'board_access_denied' }, { status: 403 });
  try { const db = requireDb(env); if (view === 'assets') return json({ boardId, view, data: (await db.prepare(`SELECT a.*,COALESCE(SUM(CASE WHEN d.ledger_type='financial' THEN d.amount_minor ELSE 0 END),0) financial_period_minor,COALESCE(SUM(CASE WHEN d.ledger_type='tax' THEN d.amount_minor ELSE 0 END),0) tax_period_minor FROM fixed_assets a LEFT JOIN depreciation_entries d ON d.asset_id=a.id WHERE a.board_id=? GROUP BY a.id ORDER BY a.asset_number`).bind(boardId).all()).results }); if (view === 'depreciation') return json({ boardId, view, data: (await db.prepare(`SELECT d.*,a.asset_number,a.name FROM depreciation_entries d JOIN fixed_assets a ON a.id=d.asset_id WHERE d.board_id=? ORDER BY d.period DESC,a.asset_number,d.ledger_type`).bind(boardId).all()).results });
    const [assets, cost, depreciation, review] = await Promise.all([db.prepare("SELECT COUNT(*) count FROM fixed_assets WHERE board_id=? AND status='active'").bind(boardId).first(),db.prepare("SELECT COALESCE(SUM(acquisition_cost_minor),0) amount_minor FROM fixed_assets WHERE board_id=? AND status='active'").bind(boardId).first(),db.prepare("SELECT COALESCE(SUM(amount_minor),0) amount_minor FROM depreciation_entries WHERE board_id=? AND ledger_type='financial'").bind(boardId).first(),db.prepare("SELECT COUNT(*) count FROM depreciation_entries WHERE board_id=? AND status IN ('calculated','review')").bind(boardId).first()]); return json({ boardId, view, data: { assets, cost, depreciation, review } });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};
export const onRequestPost: PagesFunction<Env> = async ({ env, request }) => {
  if (!authorizeWrite(request, env)) return json({ error: 'write_not_authorized' }, { status: 401 });
  try { const v = await body(request); const boardId = String(v?.boardId || ''); const action = String(v?.action || ''); const db = requireDb(env); if (!boardId || !action) return json({ error: 'boardId_and_action_required' }, { status: 400 }); if (action === 'approve_depreciation') { const entryId = String(v?.entryId || ''); const result = await db.prepare("UPDATE depreciation_entries SET status='approved',approved_by=?,approved_at=datetime('now') WHERE id=? AND board_id=? AND status IN ('calculated','review')").bind(v?.approvedBy || 'api', entryId, boardId).run(); if (!result.meta?.changes) return json({ error: 'entry_not_pending_or_found' }, { status: 409 }); return json({ ok: true, action, entryId, status: 'approved', ledgerPosting: 'not_configured' }); } return json({ error: 'unknown_action', allowed: ['approve_depreciation'] }, { status: 400 });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};
