import { authorizeBoardRead, authorizeBoardWrite, body, id, json, recordAudit, requireDb, type Env } from './_lib';
const views = new Set(['summary','assets','depreciation']);
const datePattern = /^\d{4}-\d{2}-\d{2}$/;
const periodPattern = /^\d{4}-(0[1-9]|1[0-2])$/;
const minor = (v: unknown) => Number.isSafeInteger(Number(v)) && Number(v) >= 0 ? Number(v) : null;
export const onRequestGet: PagesFunction<Env> = async ({ env, request }) => {
  const u = new URL(request.url); const boardId = (u.searchParams.get('boardId') || '').trim(); const view = u.searchParams.get('view') || 'summary';
  if (!boardId) return json({ error: 'boardId_required' }, { status: 400 }); if (!views.has(view)) return json({ error: 'unknown_view', allowed: [...views] }, { status: 400 }); if (!(await authorizeBoardRead(request, env, boardId))) return json({ error: 'board_access_denied' }, { status: 403 });
  try { const db = requireDb(env); if (view === 'assets') return json({ boardId, view, data: (await db.prepare(`SELECT a.*,COALESCE(SUM(CASE WHEN d.ledger_type='financial' THEN d.amount_minor ELSE 0 END),0) financial_period_minor,COALESCE(SUM(CASE WHEN d.ledger_type='tax' THEN d.amount_minor ELSE 0 END),0) tax_period_minor FROM fixed_assets a LEFT JOIN depreciation_entries d ON d.asset_id=a.id WHERE a.board_id=? GROUP BY a.id ORDER BY a.asset_number`).bind(boardId).all()).results }); if (view === 'depreciation') return json({ boardId, view, data: (await db.prepare(`SELECT d.*,a.asset_number,a.name FROM depreciation_entries d JOIN fixed_assets a ON a.id=d.asset_id WHERE d.board_id=? ORDER BY d.period DESC,a.asset_number,d.ledger_type`).bind(boardId).all()).results });
    const [assets, cost, depreciation, review] = await Promise.all([db.prepare("SELECT COUNT(*) count FROM fixed_assets WHERE board_id=? AND status='active'").bind(boardId).first(),db.prepare("SELECT COALESCE(SUM(acquisition_cost_minor),0) amount_minor FROM fixed_assets WHERE board_id=? AND status='active'").bind(boardId).first(),db.prepare("SELECT COALESCE(SUM(amount_minor),0) amount_minor FROM depreciation_entries WHERE board_id=? AND ledger_type='financial'").bind(boardId).first(),db.prepare("SELECT COUNT(*) count FROM depreciation_entries WHERE board_id=? AND status IN ('calculated','review')").bind(boardId).first()]); return json({ boardId, view, data: { assets, cost, depreciation, review } });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};
export const onRequestPost: PagesFunction<Env> = async ({ env, request }) => {
  try { const v = await body(request); const boardId = String(v?.boardId || '').trim(); const action = String(v?.action || '').trim(); const db = requireDb(env); if (!boardId || !action) return json({ error: 'boardId_and_action_required' }, { status: 400 }); const authorization = await authorizeBoardWrite(request, env, boardId); if (!authorization.allowed) return json({ error: 'write_not_authorized' }, { status: 401 });
    if (action === 'create_asset') { const assetNumber = String(v?.assetNumber || '').trim().slice(0, 80); const name = String(v?.name || '').trim().slice(0, 200); const category = String(v?.category || '').trim().slice(0, 100); const acquisitionDate = String(v?.acquisitionDate || ''); const cost = minor(v?.acquisitionCostMinor); const residual = minor(v?.residualValueMinor ?? 0); const life = Number(v?.usefulLifeMonths); const method = ['linear','declining_balance','none'].includes(String(v?.financialMethod)) ? String(v.financialMethod) : ''; const taxGroup = String(v?.taxGroup || '').trim(); const taxRate = Number(v?.taxRatePercent ?? 0); if (!assetNumber || !name || !category || !datePattern.test(acquisitionDate) || cost === null || residual === null || residual > cost || !Number.isInteger(life) || life < 1 || life > 1200 || !method || !Number.isFinite(taxRate) || taxRate < 0 || taxRate > 100) return json({ error: 'asset_fields_invalid' }, { status: 400 }); const exists = await db.prepare('SELECT id FROM fixed_assets WHERE board_id=? AND asset_number=?').bind(boardId, assetNumber).first(); if (exists) return json({ error: 'asset_number_exists' }, { status: 409 }); const assetId = id('fixed'); await db.prepare('INSERT INTO fixed_assets (id,board_id,asset_number,name,category,acquisition_date,acquisition_cost_minor,residual_value_minor,currency,financial_method,useful_life_months,tax_group,tax_rate_percent,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(assetId, boardId, assetNumber, name, category, acquisitionDate, cost, residual, String(v?.currency || 'NOK'), method, life, taxGroup || null, taxRate || null, 'active').run(); await recordAudit(db, { boardId, action: 'fixed_asset_created', entityType: 'fixed_asset', entityId: assetId, userId: authorization.userId || undefined, details: { assetNumber, costMinor: cost, financialMethod: method, taxGroup: taxGroup || null } }); return json({ ok: true, action, assetId, status: 'active', depreciation: 'not_calculated' }, { status: 201 }); }
    if (action === 'calculate_depreciation') { const assetId = String(v?.assetId || '').trim(); const period = String(v?.period || ''); if (!assetId || !periodPattern.test(period)) return json({ error: 'depreciation_fields_invalid' }, { status: 400 }); const asset = await db.prepare('SELECT acquisition_cost_minor,residual_value_minor,useful_life_months,financial_method,tax_rate_percent FROM fixed_assets WHERE id=? AND board_id=? AND status=\'active\'').bind(assetId, boardId).first<Record<string, unknown>>(); if (!asset) return json({ error: 'asset_not_found' }, { status: 404 }); const cost = Number(asset.acquisition_cost_minor || 0), residual = Number(asset.residual_value_minor || 0), life = Number(asset.useful_life_months || 0); const financial = asset.financial_method === 'linear' ? Math.max(0, Math.min(Math.round((cost - residual) / life), cost - residual)) : 0; const tax = Math.max(0, Math.min(Math.round(cost * Number(asset.tax_rate_percent || 0) / 100 / 12), cost)); const entries = [{ ledger: 'financial', amount: financial, accumulated: financial, value: cost - financial }, { ledger: 'tax', amount: tax, accumulated: tax, value: cost - tax }]; for (const e of entries) await db.prepare("INSERT INTO depreciation_entries (id,board_id,asset_id,period,ledger_type,amount_minor,accumulated_minor,book_value_minor,status) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(asset_id,period,ledger_type) DO UPDATE SET amount_minor=excluded.amount_minor,accumulated_minor=excluded.accumulated_minor,book_value_minor=excluded.book_value_minor,status='calculated'").bind(id('dep'), boardId, assetId, period, e.ledger, e.amount, e.accumulated, e.value, 'calculated').run(); await recordAudit(db, { boardId, action: 'depreciation_calculated', entityType: 'fixed_asset', entityId: assetId, userId: authorization.userId || undefined, details: { period, financialMinor: financial, taxMinor: tax, requiresHumanReview: true } }); return json({ ok: true, action, assetId, period, status: 'calculated', entries, requiresHumanReview: true }, { status: 201 }); }
    if (action === 'approve_depreciation') { const entryId = String(v?.entryId || '').trim(); if (!entryId) return json({ error: 'entryId_required' }, { status: 400 }); const result = await db.prepare("UPDATE depreciation_entries SET status='approved',approved_by=?,approved_at=datetime('now') WHERE id=? AND board_id=? AND status IN ('calculated','review')").bind(v?.approvedBy || authorization.userId || 'api', entryId, boardId).run(); if (!result.meta?.changes) return json({ error: 'entry_not_pending_or_found' }, { status: 409 }); await recordAudit(db, { boardId, action: 'depreciation_approved', entityType: 'depreciation_entry', entityId: entryId, userId: authorization.userId || undefined, details: { ledgerPosting: 'not_configured' } }); return json({ ok: true, action, entryId, status: 'approved', ledgerPosting: 'not_configured' }); } return json({ error: 'unknown_action', allowed: ['create_asset','calculate_depreciation','approve_depreciation'] }, { status: 400 });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};
