import { authorizeBoardRead, authorizeBoardWrite, body, json, recordAudit, requireDb, type Env } from './_lib';
const views = new Set(['summary', 'cards', 'transactions']);
const periodPattern = /^\d{4}-(0[1-9]|1[0-2])$/;
const datePattern = /^\d{4}-\d{2}-\d{2}$/;
const asMinor = (value: unknown) => Number.isSafeInteger(Number(value)) && Number(value) > 0 ? Number(value) : null;
const cardId = (prefix: string) => `${prefix}-${crypto.randomUUID()}`;
export const onRequestGet: PagesFunction<Env> = async ({ env, request }) => {
  const u = new URL(request.url); const boardId = (u.searchParams.get('boardId') || '').trim(); const view = u.searchParams.get('view') || 'summary';
  if (!boardId) return json({ error: 'boardId_required' }, { status: 400 });
  if (!views.has(view)) return json({ error: 'unknown_view', allowed: [...views] }, { status: 400 });
  if (!(await authorizeBoardRead(request, env, boardId))) return json({ error: 'board_access_denied' }, { status: 403 });
  try { const db = requireDb(env); const q: Record<string, string> = {
    cards: `SELECT c.*,p.name holder_name FROM corporate_cards c LEFT JOIN people p ON p.id=c.holder_id WHERE c.board_id=? ORDER BY c.card_name`,
    transactions: `SELECT t.*,c.card_name,p.name holder_name FROM card_transactions t LEFT JOIN corporate_cards c ON c.id=t.card_id LEFT JOIN people p ON p.id=c.holder_id WHERE t.board_id=? ORDER BY t.transaction_date DESC`,
  }; if (view !== 'summary') return json({ boardId, view, data: (await db.prepare(q[view]).bind(boardId).all()).results });
    const [cards, transactions, missingReceipts, review] = await Promise.all([
      db.prepare("SELECT COUNT(*) count FROM corporate_cards WHERE board_id=? AND status IN ('active','proposed')").bind(boardId).first(),
      db.prepare("SELECT COUNT(*) count,COALESCE(SUM(amount_minor),0) amount_minor FROM card_transactions WHERE board_id=? AND status NOT IN ('reconciled','rejected')").bind(boardId).first(),
      db.prepare("SELECT COUNT(*) count,COALESCE(SUM(amount_minor),0) amount_minor FROM card_transactions WHERE board_id=? AND status='needs_receipt'").bind(boardId).first(),
      db.prepare("SELECT COUNT(*) count FROM card_transactions WHERE board_id=? AND status='ready_for_review'").bind(boardId).first(),
    ]); return json({ boardId, view, data: { cards, transactions, missingReceipts, review } });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};
export const onRequestPost: PagesFunction<Env> = async ({ env, request }) => {
  try { const v = await body(request); const boardId = String(v?.boardId || '').trim(); const action = String(v?.action || '').trim(); const db = requireDb(env); if (!boardId || !action) return json({ error: 'boardId_and_action_required' }, { status: 400 }); const authorization = await authorizeBoardWrite(request, env, boardId); if (!authorization.allowed) return json({ error: 'write_not_authorized' }, { status: 401 });
    if (action === 'attach_receipt') { const transactionId = String(v?.transactionId || ''); const ref = String(v?.receiptRef || '').trim(); if (!ref) return json({ error: 'receipt_ref_required' }, { status: 400 }); const result = await db.prepare("UPDATE card_transactions SET receipt_ref=?,status='ready_for_review' WHERE id=? AND board_id=? AND status='needs_receipt'").bind(ref, transactionId, boardId).run(); if (!result.meta?.changes) return json({ error: 'transaction_not_missing_receipt_or_found' }, { status: 409 }); await recordAudit(db, { boardId, action: 'card_receipt_attached', entityType: 'card_transaction', entityId: transactionId, userId: authorization.userId || undefined, details: { status: 'ready_for_review' } }); return json({ ok: true, action, transactionId, status: 'ready_for_review' }); }
    if (action === 'approve_transaction') { const transactionId = String(v?.transactionId || ''); const result = await db.prepare("UPDATE card_transactions SET status='approved',reviewed_by=?,reviewed_at=datetime('now') WHERE id=? AND board_id=? AND status='ready_for_review'").bind(v?.reviewedBy || authorization.userId || 'api', transactionId, boardId).run(); if (!result.meta?.changes) return json({ error: 'transaction_not_ready_or_found' }, { status: 409 }); await recordAudit(db, { boardId, action: 'card_transaction_approved', entityType: 'card_transaction', entityId: transactionId, userId: authorization.userId || undefined, details: { ledgerPosting: 'controlled_human_posting' } }); return json({ ok: true, action, transactionId, status: 'approved', ledgerPosting: 'controlled_human_posting' }); }
    if (action === 'post_transaction') {
      const transactionId = String(v?.transactionId || '').trim(); const transaction = await db.prepare("SELECT t.*,c.card_name FROM card_transactions t LEFT JOIN corporate_cards c ON c.id=t.card_id WHERE t.id=? AND t.board_id=? AND t.status='approved' AND t.posted_voucher_id IS NULL").bind(transactionId, boardId).first<Record<string, unknown>>(); if (!transaction) return json({ error: 'transaction_not_approved_or_found' }, { status: 409 });
      const bankLedgerAccountId = String(v?.cardLedgerAccountId || '').trim(), counterAccountId = String(v?.counterAccountId || '').trim(); const amount = asMinor(transaction.amount_minor); const date = String(transaction.transaction_date || '').trim(), period = date.slice(0, 7); if (!bankLedgerAccountId || !counterAccountId || bankLedgerAccountId === counterAccountId) return json({ error: 'card_and_counter_accounts_required' }, { status: 400 }); if (amount === null || !datePattern.test(date) || !periodPattern.test(period)) return json({ error: 'card_transaction_fields_invalid' }, { status: 400 }); if (await db.prepare("SELECT 1 FROM accounting_periods WHERE board_id=? AND period=? AND status='locked'").bind(boardId, period).first()) return json({ error: 'period_locked', period }, { status: 409 }); const accounts = (await db.prepare('SELECT id FROM ledger_accounts WHERE board_id=? AND active=1 AND id IN (?,?)').bind(boardId, bankLedgerAccountId, counterAccountId).all()).results; if (accounts.length !== 2) return json({ error: 'ledger_account_not_found' }, { status: 400 });
      const externalReference = `card:${transactionId}`; const existing = await db.prepare('SELECT id,voucher_number,period FROM vouchers WHERE board_id=? AND external_reference=?').bind(boardId, externalReference).first<{ id: string; voucher_number: number; period: string }>(); if (existing) return json({ ok: true, action, transactionId, status: 'reconciled', voucherId: existing.id, voucherNumber: Number(existing.voucher_number), period: existing.period, idempotent: true });
      const voucherId = cardId('voucher'); const statements = [db.prepare('INSERT INTO voucher_sequences (board_id,next_number) SELECT ?,COALESCE(MAX(voucher_number),0)+1 FROM vouchers WHERE board_id=? ON CONFLICT(board_id) DO NOTHING').bind(boardId, boardId), db.prepare("UPDATE voucher_sequences SET next_number=next_number+1,updated_at=datetime('now') WHERE board_id=?").bind(boardId), db.prepare('INSERT INTO vouchers (id,board_id,voucher_number,voucher_date,period,description,source,status,external_reference,created_by) SELECT ?,?,next_number-1,?,?,?,?,?,?,? FROM voucher_sequences WHERE board_id=?').bind(voucherId, boardId, date, period, `Firmakort ${String(transaction.merchant || '').slice(0, 160)}`, 'card_reconciliation', 'posted', externalReference, authorization.userId || 'authorized-user', boardId), db.prepare('INSERT INTO voucher_lines (id,voucher_id,account_id,description,debit_minor,credit_minor,vat_code) VALUES (?,?,?,?,?,?,?)').bind(cardId('line'), voucherId, counterAccountId, `Kjøp hos ${String(transaction.merchant || '').slice(0, 160)}`, amount, 0, null), db.prepare('INSERT INTO voucher_lines (id,voucher_id,account_id,description,debit_minor,credit_minor,vat_code) VALUES (?,?,?,?,?,?,?)').bind(cardId('line'), voucherId, bankLedgerAccountId, `Firmakort ${String(transaction.card_name || '').slice(0, 120)}`, 0, amount, null)]; await db.batch(statements); const created = await db.prepare('SELECT voucher_number FROM vouchers WHERE id=? AND board_id=?').bind(voucherId, boardId).first<{ voucher_number: number }>(); if (!created) return json({ error: 'card_voucher_not_created' }, { status: 503 }); await db.prepare("UPDATE card_transactions SET posted_voucher_id=?,status='reconciled',reviewed_at=COALESCE(reviewed_at,datetime('now')) WHERE id=? AND board_id=? AND status='approved' AND posted_voucher_id IS NULL").bind(voucherId, transactionId, boardId).run(); await recordAudit(db, { boardId, action: 'card_transaction_posted', entityType: 'card_transaction', entityId: transactionId, userId: authorization.userId || undefined, details: { voucherId, voucherNumber: created.voucher_number, period, cardLedgerAccountId: bankLedgerAccountId, counterAccountId, amountMinor: amount } }); return json({ ok: true, action, transactionId, status: 'reconciled', voucherId, voucherNumber: Number(created.voucher_number), period }, { status: 201 });
    }
    return json({ error: 'unknown_action', allowed: ['attach_receipt', 'approve_transaction', 'post_transaction'] }, { status: 400 });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};
