import { authorizeBoardRead, authorizeWrite, body, id, json, requireDb, type Env } from './_lib';

const views = new Set(['summary','pipeline','quotes','rooms','subscriptions','cases']);
export const onRequestGet: PagesFunction<Env> = async ({ env, request }) => {
  const url=new URL(request.url);const boardId=(url.searchParams.get('boardId')||'').trim();const view=url.searchParams.get('view')||'summary';
  if(!boardId)return json({error:'boardId_required'},{status:400});if(!views.has(view))return json({error:'unknown_view',allowed:[...views]},{status:400});if(!(await authorizeBoardRead(request,env,boardId)))return json({error:'board_access_denied'},{status:403});
  try{const db=requireDb(env);
    if(view==='pipeline')return json({boardId,view,data:(await db.prepare(`SELECT a.id,a.company_name,a.stage,a.next_action,a.estimated_value_minor,a.currency,p.name AS owner_name FROM crm_accounts a LEFT JOIN people p ON p.id=a.owner_id WHERE a.board_id=? ORDER BY CASE a.stage WHEN 'won' THEN 1 WHEN 'proposal' THEN 2 WHEN 'qualified' THEN 3 ELSE 4 END,a.created_at DESC`).bind(boardId).all()).results});
    if(view==='quotes')return json({boardId,view,data:(await db.prepare(`SELECT q.id,q.quote_number,q.title,q.status,q.total_minor,q.currency,q.valid_until,q.approval_required,a.company_name,p.name AS owner_name FROM quotes q LEFT JOIN crm_accounts a ON a.id=q.account_id LEFT JOIN people p ON p.id=q.owner_id WHERE q.board_id=? ORDER BY q.created_at DESC`).bind(boardId).all()).results});
    if(view==='rooms')return json({boardId,view,data:(await db.prepare(`SELECT r.id,r.name,r.status,r.buyer_contact,r.expires_at,a.company_name,q.quote_number FROM sales_rooms r LEFT JOIN crm_accounts a ON a.id=r.account_id LEFT JOIN quotes q ON q.id=r.quote_id WHERE r.board_id=? ORDER BY r.created_at DESC`).bind(boardId).all()).results});
    if(view==='subscriptions')return json({boardId,view,data:(await db.prepare(`SELECT s.id,s.plan_name,s.status,s.recurring_minor,s.currency,s.interval,s.start_date,s.renewal_date,a.company_name FROM customer_subscriptions s JOIN crm_accounts a ON a.id=s.account_id WHERE s.board_id=? ORDER BY s.renewal_date`).bind(boardId).all()).results});
    if(view==='cases')return json({boardId,view,data:(await db.prepare(`SELECT c.id,c.case_number,c.title,c.priority,c.status,c.channel,c.first_response_due,c.resolution_due,c.first_responded_at,c.resolved_at,a.company_name,p.name AS assignee_name,CASE WHEN c.status IN ('resolved','closed') THEN 'closed' WHEN c.first_responded_at IS NULL AND c.first_response_due IS NOT NULL AND c.first_response_due < datetime('now') THEN 'first_response_breached' WHEN c.resolution_due IS NOT NULL AND c.resolution_due < datetime('now') THEN 'resolution_breached' WHEN c.first_responded_at IS NULL THEN 'awaiting_first_response' ELSE 'within_sla' END AS sla_state FROM customer_cases c LEFT JOIN crm_accounts a ON a.id=c.account_id LEFT JOIN people p ON p.id=c.assignee_id WHERE c.board_id=? ORDER BY CASE c.priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 ELSE 3 END,c.created_at DESC`).bind(boardId).all()).results});
    const [pipeline,quotes,rooms,activeSubs,cases,slaBreaches]=await Promise.all([
      db.prepare("SELECT COUNT(*) AS count,COALESCE(SUM(estimated_value_minor),0) AS value_minor FROM crm_accounts WHERE board_id=? AND stage NOT IN ('won','lost')").bind(boardId).first(),
      db.prepare("SELECT COUNT(*) AS count FROM quotes WHERE board_id=? AND status IN ('pending_approval','sent')").bind(boardId).first(),
      db.prepare("SELECT COUNT(*) AS count FROM sales_rooms WHERE board_id=? AND status='active'").bind(boardId).first(),
      db.prepare("SELECT COUNT(*) AS count,COALESCE(SUM(recurring_minor),0) AS mrr_minor FROM customer_subscriptions WHERE board_id=? AND status IN ('trial','active')").bind(boardId).first(),
      db.prepare("SELECT COUNT(*) AS count FROM customer_cases WHERE board_id=? AND status NOT IN ('resolved','closed')").bind(boardId).first(),
      db.prepare("SELECT COUNT(*) AS count FROM customer_cases WHERE board_id=? AND status NOT IN ('resolved','closed') AND ((first_responded_at IS NULL AND first_response_due IS NOT NULL AND first_response_due < datetime('now')) OR (resolution_due IS NOT NULL AND resolution_due < datetime('now'))) ").bind(boardId).first(),
    ]);return json({boardId,view,data:{pipeline,quotes,rooms,activeSubs,cases,slaBreaches}});
  }catch(error){return json({error:'database_unavailable',detail:error instanceof Error?error.message:'unknown'},{status:503});}
};

export const onRequestPost: PagesFunction<Env> = async ({ env, request }) => {
  if(!authorizeWrite(request,env))return json({error:'write_not_authorized'},{status:401});
  try{const value=await body(request);const boardId=String(value?.boardId||'').trim();const action=String(value?.action||'');if(!boardId||!action)return json({error:'boardId_and_action_required'},{status:400});const db=requireDb(env);
    if(action==='approve_quote'){const quoteId=String(value?.quoteId||'');if(!quoteId)return json({error:'quoteId_required'},{status:400});const result=await db.prepare("UPDATE quotes SET status='approved',approved_by=?,approved_at=datetime('now'),updated_at=datetime('now') WHERE id=? AND board_id=? AND status='pending_approval'").bind(String(value?.approvedBy||'api'),quoteId,boardId).run();if(!(result.meta?.changes))return json({error:'quote_not_pending_approval'},{status:409});return json({ok:true,action,quoteId,status:'approved',nextAction:'human-controlled send',requiresHumanReview:false});}
    if(action==='send_quote'){const quoteId=String(value?.quoteId||'');if(!quoteId)return json({error:'quoteId_required'},{status:400});const q=await db.prepare("SELECT status FROM quotes WHERE id=? AND board_id=?").bind(quoteId,boardId).first<Record<string,unknown>>();if(q?.status!=='approved')return json({error:'quote_must_be_approved'},{status:409});await db.prepare("UPDATE quotes SET status='sent',sent_at=datetime('now'),updated_at=datetime('now') WHERE id=? AND board_id=?").bind(quoteId,boardId).run();return json({ok:true,action,quoteId,status:'sent',externalDelivery:'not_configured'});}
    if(action==='create_case'){const title=String(value?.title||'').trim();const channel=String(value?.channel||'portal');const priority=String(value?.priority||'medium');if(!title)return json({error:'title_required'},{status:400});if(!['portal','email','phone','internal'].includes(channel)||!['critical','high','medium','low'].includes(priority))return json({error:'invalid_channel_or_priority'},{status:400});const row=await db.prepare('SELECT COALESCE(MAX(case_number),3000)+1 AS next FROM customer_cases WHERE board_id=?').bind(boardId).first<Record<string,unknown>>();const caseId=id('case');await db.prepare("INSERT INTO customer_cases (id,board_id,account_id,case_number,title,description,channel,priority,status,assignee_id,first_response_due,resolution_due) VALUES (?,?,?,?,?,?,?,?,'open',?,?,?)").bind(caseId,boardId,value?.accountId||null,Number(row?.next||3001),title,String(value?.description||''),channel,priority,value?.assigneeId||null,value?.firstResponseDue||null,value?.resolutionDue||null).run();return json({ok:true,action,id:caseId,status:'open',slaState:'awaiting_first_response'}, {status:201});}
    if(action==='record_case_response'){const caseId=String(value?.caseId||'').trim();if(!caseId)return json({error:'caseId_required'},{status:400});const result=await db.prepare("UPDATE customer_cases SET first_responded_at=COALESCE(first_responded_at,datetime('now')),status=CASE WHEN status='open' THEN 'in_progress' ELSE status END,updated_at=datetime('now') WHERE id=? AND board_id=? AND status NOT IN ('resolved','closed')").bind(caseId,boardId).run();if(!(result.meta?.changes))return json({error:'case_not_open'},{status:409});return json({ok:true,action,caseId,status:'in_progress',slaState:'within_sla',externalDelivery:'not_configured'});}
    if(action==='update_case_status'){const caseId=String(value?.caseId||'').trim();const nextStatus=String(value?.status||'').trim();if(!caseId||!['open','in_progress','waiting_customer','resolved','closed'].includes(nextStatus))return json({error:'caseId_and_valid_status_required'},{status:400});const result=await db.prepare("UPDATE customer_cases SET status=?,resolved_at=CASE WHEN ? IN ('resolved','closed') THEN COALESCE(resolved_at,datetime('now')) ELSE resolved_at END,updated_at=datetime('now') WHERE id=? AND board_id=?").bind(nextStatus,nextStatus,caseId,boardId).run();if(!(result.meta?.changes))return json({error:'case_not_found'},{status:404});return json({ok:true,action,caseId,status:nextStatus,requiresHumanReview:nextStatus==='resolved'||nextStatus==='closed'});}
    if(action==='resolve_case'){const caseId=String(value?.caseId||'');if(!caseId)return json({error:'caseId_required'},{status:400});const result=await db.prepare("UPDATE customer_cases SET status='resolved',resolved_at=datetime('now'),updated_at=datetime('now') WHERE id=? AND board_id=? AND status NOT IN ('resolved','closed')").bind(caseId,boardId).run();if(!(result.meta?.changes))return json({error:'case_not_open'},{status:409});return json({ok:true,action,caseId,status:'resolved'});}
    return json({error:'unknown_action',allowed:['approve_quote','send_quote','create_case','record_case_response','update_case_status','resolve_case']},{status:400});
  }catch(error){return json({error:'database_unavailable',detail:error instanceof Error?error.message:'unknown'},{status:503});}
};
