import { authorizeBoardRead, authorizeBoardWrite, body, id, json, recordAudit, requireDb, type Env } from './_lib';

const views = new Set(['summary', 'fleet', 'trips', 'maintenance', 'facilities', 'facility_tasks', 'projects', 'rates', 'time', 'people', 'wip', 'invoice_drafts']);
const txt = (v: unknown, max = 200) => String(v ?? '').trim().slice(0, max);
const isoDate = (v: unknown) => /^\d{4}-\d{2}-\d{2}$/.test(String(v ?? '')) ? String(v) : null;

export const onRequestGet: PagesFunction<Env> = async ({ env, request }) => {
  const u = new URL(request.url); const boardId = txt(u.searchParams.get('boardId')); const view = u.searchParams.get('view') || 'summary';
  if (!boardId) return json({ error: 'boardId_required' }, { status: 400 }); if (!views.has(view)) return json({ error: 'unknown_view', allowed: [...views] }, { status: 400 }); if (!(await authorizeBoardRead(request, env, boardId))) return json({ error: 'board_access_denied' }, { status: 403 });
  try {
    const db = requireDb(env); const queries: Record<string, string> = { fleet: 'SELECT v.*,p.name owner_name FROM fleet_vehicles v LEFT JOIN people p ON p.id=v.owner_id WHERE v.board_id=? ORDER BY v.registration', trips: 'SELECT t.*,v.registration,p.name driver_name FROM trip_logs t JOIN fleet_vehicles v ON v.id=t.vehicle_id LEFT JOIN people p ON p.id=t.driver_id WHERE t.board_id=? ORDER BY t.trip_date DESC', maintenance: 'SELECT m.*,v.registration FROM fleet_maintenance m JOIN fleet_vehicles v ON v.id=m.vehicle_id WHERE m.board_id=? ORDER BY m.due_date', facilities: 'SELECT f.*,p.name owner_name FROM facilities f LEFT JOIN people p ON p.id=f.owner_id WHERE f.board_id=? ORDER BY f.name', facility_tasks: 'SELECT t.*,f.name facility_name FROM facility_tasks t JOIN facilities f ON f.id=t.facility_id WHERE t.board_id=? ORDER BY t.due_date', projects: 'SELECT pr.*,a.company_name FROM projects pr LEFT JOIN crm_accounts a ON a.id=pr.customer_account_id WHERE pr.board_id=? ORDER BY pr.created_at DESC', rates: 'SELECT r.*,p.name AS project_name,COALESCE(c.cost_hourly_minor,0) cost_hourly_minor,c.source AS cost_source FROM project_rates r JOIN projects p ON p.id=r.project_id LEFT JOIN project_rate_costs c ON c.rate_id=r.id WHERE r.board_id=? ORDER BY p.code,r.valid_from DESC,r.role', time: 'SELECT t.*,pr.code project_code,pr.name project_name,p.name person_name FROM time_entries t JOIN projects pr ON pr.id=t.project_id JOIN people p ON p.id=t.person_id WHERE t.board_id=? ORDER BY t.work_date DESC', people: "SELECT id,name,role,department,employment_status FROM people WHERE board_id=? AND employment_status='active' ORDER BY name", wip: 'SELECT pr.id,pr.code,pr.name,pr.billing_model,pr.budget_minor,pr.currency,a.company_name,COALESCE(SUM(CASE WHEN t.billable=1 AND t.status IN (\'submitted\',\'approved\') THEN t.minutes ELSE 0 END),0) minutes,COALESCE(SUM(CASE WHEN t.billable=1 AND t.status IN (\'submitted\',\'approved\') THEN t.minutes*COALESCE(t.rate_minor,0)/60 ELSE 0 END),0) amount_minor,COALESCE(SUM(CASE WHEN t.billable=1 AND t.status IN (\'submitted\',\'approved\') THEN t.minutes*COALESCE((SELECT pc.cost_hourly_minor FROM project_rate_costs pc JOIN project_rates rr ON rr.id=pc.rate_id WHERE rr.project_id=pr.id AND rr.board_id=pr.board_id ORDER BY rr.valid_from DESC LIMIT 1),0)/60 ELSE 0 END),0) cost_minor,COUNT(CASE WHEN t.billable=1 AND t.status IN (\'submitted\',\'approved\') THEN t.id END) entry_count FROM projects pr LEFT JOIN crm_accounts a ON a.id=pr.customer_account_id LEFT JOIN time_entries t ON t.project_id=pr.id AND t.board_id=pr.board_id WHERE pr.board_id=? GROUP BY pr.id ORDER BY pr.code', invoice_drafts: 'SELECT d.*,pr.code,pr.name,a.company_name FROM project_invoice_drafts d JOIN projects pr ON pr.id=d.project_id LEFT JOIN crm_accounts a ON a.id=pr.customer_account_id WHERE d.board_id=? ORDER BY d.period DESC,d.created_at DESC' };
    if (view !== 'summary') return json({ boardId, view, data: (await db.prepare(queries[view]).bind(boardId).all()).results });
    const [fleet, trips, maintenance, facilities, projects, time, wip, drafts] = await Promise.all([db.prepare("SELECT COUNT(*) count FROM fleet_vehicles WHERE board_id=? AND status='active'").bind(boardId).first(), db.prepare("SELECT COUNT(*) count FROM trip_logs WHERE board_id=? AND status='draft'").bind(boardId).first(), db.prepare("SELECT COUNT(*) count FROM fleet_maintenance WHERE board_id=? AND status IN ('scheduled','overdue')").bind(boardId).first(), db.prepare("SELECT COUNT(*) count FROM facility_tasks WHERE board_id=? AND status NOT IN ('complete')").bind(boardId).first(), db.prepare("SELECT COUNT(*) count FROM projects WHERE board_id=? AND status='active'").bind(boardId).first(), db.prepare("SELECT COUNT(*) count,COALESCE(SUM(minutes),0) minutes FROM time_entries WHERE board_id=? AND status IN ('submitted','approved')").bind(boardId).first(), db.prepare("SELECT COUNT(*) count,COALESCE(SUM(CASE WHEN billable=1 AND status IN ('submitted','approved') THEN minutes*COALESCE(rate_minor,0)/60 ELSE 0 END),0) amount_minor,COALESCE(SUM(CASE WHEN billable=1 AND status IN ('submitted','approved') THEN minutes*COALESCE((SELECT cost_hourly_minor FROM project_rate_costs pc JOIN project_rates pr ON pr.id=pc.rate_id WHERE pr.project_id=time_entries.project_id AND pr.board_id=time_entries.board_id ORDER BY pr.valid_from DESC LIMIT 1),0)/60 ELSE 0 END),0) cost_minor FROM time_entries WHERE board_id=?").bind(boardId).first(), db.prepare("SELECT COUNT(*) count,COALESCE(SUM(amount_minor),0) amount_minor FROM project_invoice_drafts WHERE board_id=? AND status NOT IN ('sent','cancelled')").bind(boardId).first()]);
    return json({ boardId, view, data: { fleet, trips, maintenance, facilities, projects, time, wip, drafts } });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};

export const onRequestPost: PagesFunction<Env> = async ({ env, request }) => {
  try {
    const value = await body(request); const boardId = txt(value?.boardId); const action = txt(value?.action, 50); const db = requireDb(env); if (!boardId || !action) return json({ error: 'boardId_and_action_required' }, { status: 400 }); const auth = await authorizeBoardWrite(request, env, boardId); if (!auth.allowed) return json({ error: 'write_not_authorized' }, { status: 401 }); const actor = auth.userId || 'api'; const audit = (entityType: string, entityId: string, details: Record<string, unknown> = {}) => recordAudit(db, { boardId, action: `field_${action}`, entityType, entityId, userId: auth.userId || undefined, details });
    if (action === 'classify_trip') { const tripId = txt(value?.tripId, 100); const tripType = txt(value?.tripType, 20); if (!['business', 'private', 'commute', 'unknown'].includes(tripType)) return json({ error: 'invalid_trip_type' }, { status: 400 }); const result = await db.prepare("UPDATE trip_logs SET trip_type=?,status='classified',tax_basis=? WHERE id=? AND board_id=? AND status='draft'").bind(tripType, txt(value?.taxBasis, 200) || null, tripId, boardId).run(); if (!result.meta?.changes) return json({ error: 'trip_not_draft_or_found' }, { status: 409 }); await audit('trip_log', tripId, { status: 'classified', tripType, requiresHumanApproval: true }); return json({ ok: true, action, tripId, status: 'classified', requiresHumanApproval: true }); }
    if (action === 'complete_maintenance') { const maintenanceId = txt(value?.maintenanceId, 100); const result = await db.prepare("UPDATE fleet_maintenance SET status='complete' WHERE id=? AND board_id=? AND status IN ('scheduled','booked','overdue')").bind(maintenanceId, boardId).run(); if (!result.meta?.changes) return json({ error: 'maintenance_not_open_or_found' }, { status: 409 }); await audit('fleet_maintenance', maintenanceId, { status: 'complete' }); return json({ ok: true, action, maintenanceId, status: 'complete' }); }
    if (action === 'complete_facility_task') { const taskId = txt(value?.taskId, 100); const evidenceRef = txt(value?.evidenceRef, 500) || null; const result = await db.prepare("UPDATE facility_tasks SET status='complete',evidence_ref=? WHERE id=? AND board_id=? AND status IN ('open','scheduled','overdue')").bind(evidenceRef, taskId, boardId).run(); if (!result.meta?.changes) return json({ error: 'facility_task_not_open_or_found' }, { status: 409 }); await audit('facility_task', taskId, { status: 'complete', evidenceRef: evidenceRef || undefined, externalProcurement: 'not_configured' }); return json({ ok: true, action, taskId, status: 'complete', externalProcurement: 'not_configured' }); }
    if (action === 'create_time_entry') { const projectId = txt(value?.projectId, 100); const personId = txt(value?.personId, 100); const workDate = isoDate(value?.workDate); const minutes = Number(value?.minutes); if (!workDate || !Number.isInteger(minutes) || minutes < 1 || minutes > 1440) return json({ error: 'invalid_time_entry' }, { status: 400 }); const [project, person] = await Promise.all([db.prepare("SELECT id FROM projects WHERE id=? AND board_id=? AND status IN ('active','draft')").bind(projectId, boardId).first(), db.prepare("SELECT id FROM people WHERE id=? AND board_id=? AND employment_status='active'").bind(personId, boardId).first()]); if (!project || !person) return json({ error: 'project_or_person_not_found' }, { status: 404 }); const rate = await db.prepare('SELECT hourly_minor FROM project_rates WHERE project_id=? AND board_id=? ORDER BY valid_from DESC LIMIT 1').bind(projectId, boardId).first<{ hourly_minor: number }>(); const entryId = id('time'); await db.prepare('INSERT INTO time_entries (id,board_id,project_id,person_id,work_date,minutes,description,billable,status,rate_minor) VALUES (?,?,?,?,?,?,?,? ,\'draft\',?)').bind(entryId, boardId, projectId, personId, workDate, minutes, txt(value?.description, 500) || null, value?.billable === false || value?.billable === 'false' ? 0 : 1, Number(rate?.hourly_minor || 0)).run(); await audit('time_entry', entryId, { status: 'draft', minutes, billable: value?.billable === false || value?.billable === 'false' ? false : true }); return json({ ok: true, action, entryId, status: 'draft', rateMinor: Number(rate?.hourly_minor || 0) }, { status: 201 }); }
    if (action === 'submit_time') { const entryId = txt(value?.entryId, 100); const result = await db.prepare("UPDATE time_entries SET status='submitted' WHERE id=? AND board_id=? AND status='draft'").bind(entryId, boardId).run(); if (!result.meta?.changes) return json({ error: 'time_not_draft_or_found' }, { status: 409 }); await audit('time_entry', entryId, { status: 'submitted', requiresHumanApproval: true }); return json({ ok: true, action, entryId, status: 'submitted', requiresHumanApproval: true }); }
    if (action === 'prepare_invoice') { const projectId = txt(value?.projectId, 100); const requestedPeriod = String(value?.period || ''); const period = isoDate(requestedPeriod) || (/^\d{4}-\d{2}$/.test(requestedPeriod) ? requestedPeriod : new Date().toISOString().slice(0, 7)); const aggregate = await db.prepare("SELECT COALESCE(SUM(minutes),0) source_minutes,COALESCE(SUM(minutes*COALESCE(rate_minor,0)/60),0) amount_minor FROM time_entries WHERE board_id=? AND project_id=? AND billable=1 AND status IN ('submitted','approved')").bind(boardId, projectId).first<{ source_minutes: number; amount_minor: number }>(); if (!aggregate || Number(aggregate.source_minutes) <= 0) return json({ error: 'no_billable_time_ready' }, { status: 409 }); const draftId = id('invprep'); await db.prepare("INSERT INTO project_invoice_drafts (id,board_id,project_id,period,source_minutes,amount_minor,currency,status,created_by) VALUES (?,?,?,?,?,?, 'NOK','prepared',?)").bind(draftId, boardId, projectId, period, aggregate.source_minutes, aggregate.amount_minor, actor).run(); await audit('project_invoice_draft', draftId, { status: 'prepared', externalInvoicing: 'not_configured' }); return json({ ok: true, action, draftId, status: 'prepared', sourceMinutes: aggregate.source_minutes, amountMinor: aggregate.amount_minor, externalInvoicing: 'not_configured' }, { status: 201 }); }
    if (action === 'approve_invoice_draft') { const draftId = txt(value?.draftId, 100); const result = await db.prepare("UPDATE project_invoice_drafts SET status='approved',approved_by=?,approved_at=datetime('now') WHERE id=? AND board_id=? AND status IN ('prepared','review')").bind(actor, draftId, boardId).run(); if (!result.meta?.changes) return json({ error: 'invoice_draft_not_found_or_already_approved' }, { status: 409 }); await audit('project_invoice_draft', draftId, { status: 'approved', externalInvoicing: 'not_configured' }); return json({ ok: true, action, draftId, status: 'approved', externalInvoicing: 'not_configured' }); }
    if (action === 'approve_time') { const entryId = txt(value?.entryId, 100); const result = await db.prepare("UPDATE time_entries SET status='approved',approved_by=?,approved_at=datetime('now') WHERE id=? AND board_id=? AND status='submitted'").bind(actor, entryId, boardId).run(); if (!result.meta?.changes) return json({ error: 'time_not_submitted_or_found' }, { status: 409 }); await audit('time_entry', entryId, { status: 'approved' }); return json({ ok: true, action, entryId, status: 'approved' }); }
    return json({ error: 'unknown_action', allowed: ['classify_trip', 'complete_maintenance', 'complete_facility_task', 'create_time_entry', 'submit_time', 'prepare_invoice', 'approve_invoice_draft', 'approve_time'] }, { status: 400 });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};
