import { authorizeBoardRead, authorizeBoardWrite, body, id, json, recordAudit, requireDb, sha256, type Env } from './_lib';

const periodPattern = /^\d{4}-(0[1-9]|1[0-2])$/;
const datePattern = /^\d{4}-\d{2}-\d{2}$/;
const text = (value: unknown, max = 240) => String(value ?? '').trim().slice(0, max);
const integerMinor = (value: unknown) => Number.isSafeInteger(Number(value)) && Number(value) >= 0 ? Number(value) : null;
type PostingLine = { accountId: string; description: string; debitMinor: number; creditMinor: number; vatCode?: string | null };

async function accountsExist(db: D1Database, boardId: string, accountIds: string[]) {
  const unique = [...new Set(accountIds.filter(Boolean))]; if (!unique.length) return false;
  const placeholders = unique.map(() => '?').join(',');
  const rows = (await db.prepare(`SELECT id FROM ledger_accounts WHERE board_id=? AND active=1 AND id IN (${placeholders})`).bind(boardId, ...unique).all()).results as Record<string, unknown>[];
  return rows.length === unique.length;
}

async function nextVoucher(db: D1Database, boardId: string, voucher: { voucherDate: string; period: string; description: string; source: string; externalReference: string; createdBy: string }, lines: PostingLine[]) {
  const voucherId = id('voucher');
  let debit = 0; let credit = 0;
  for (const line of lines) { debit += line.debitMinor; credit += line.creditMinor; }
  if (debit !== credit || debit <= 0) throw new Error('posting_not_balanced');
  const statements = [
    db.prepare('INSERT INTO voucher_sequences (board_id,next_number) SELECT ?,COALESCE(MAX(voucher_number),0)+1 FROM vouchers WHERE board_id=? ON CONFLICT(board_id) DO NOTHING').bind(boardId, boardId),
    db.prepare("UPDATE voucher_sequences SET next_number=next_number+1,updated_at=datetime('now') WHERE board_id=?").bind(boardId),
    db.prepare('INSERT INTO vouchers (id,board_id,voucher_number,voucher_date,period,description,source,status,external_reference,created_by) SELECT ?,?,next_number-1,?,?,?,?,?,?,? FROM voucher_sequences WHERE board_id=?').bind(voucherId, boardId, voucher.voucherDate, voucher.period, voucher.description, voucher.source, 'posted', voucher.externalReference, voucher.createdBy, boardId),
  ];
  for (const line of lines) statements.push(db.prepare('INSERT INTO voucher_lines (id,voucher_id,account_id,description,debit_minor,credit_minor,vat_code) VALUES (?,?,?,?,?,?,?)').bind(id('line'), voucherId, line.accountId, line.description, line.debitMinor, line.creditMinor, line.vatCode || null));
  await db.batch(statements);
  const created = await db.prepare('SELECT voucher_number FROM vouchers WHERE id=? AND board_id=?').bind(voucherId, boardId).first<{ voucher_number: number }>();
  if (!created) throw new Error('voucher_created_without_number');
  return { voucherId, voucherNumber: Number(created.voucher_number), debit, credit };
}

export const onRequestGet: PagesFunction<Env> = async ({ env, request }) => {
  const u = new URL(request.url); const boardId = text(u.searchParams.get('boardId'), 100); const view = u.searchParams.get('view') || 'summary';
  if (!boardId) return json({ error: 'boardId_required' }, { status: 400 }); if (!['summary', 'proposals'].includes(view)) return json({ error: 'unknown_view', allowed: ['summary', 'proposals'] }, { status: 400 }); if (!(await authorizeBoardRead(request, env, boardId))) return json({ error: 'board_access_denied' }, { status: 403 });
  try {
    const db = requireDb(env);
    if (view === 'proposals') {
      const [invoiceRows, payrollRows, creditRows] = await Promise.all([
        db.prepare("SELECT p.*,CASE WHEN p.source_type='sales_invoice' THEN s.invoice_number ELSE si.invoice_number END AS source_reference,CASE WHEN p.source_type='sales_invoice' THEN s.description ELSE si.supplier_name END AS source_label FROM posting_proposals p LEFT JOIN sales_invoices s ON p.source_type='sales_invoice' AND s.id=p.source_id LEFT JOIN supplier_invoices si ON p.source_type='supplier_invoice' AND si.id=p.source_id WHERE p.board_id=?").bind(boardId).all(),
        db.prepare("SELECT p.*, 'payroll_run' AS source_type, r.period AS source_reference, ('Lønn ' || r.period) AS source_label, p.payroll_run_id AS source_id FROM payroll_posting_proposals p JOIN payroll_runs r ON r.id=p.payroll_run_id WHERE p.board_id=?").bind(boardId).all(),
        db.prepare("SELECT p.*,'sales_credit_note' AS source_type,c.credit_note_number AS source_reference,('Kreditnota for ' || i.invoice_number) AS source_label,p.credit_note_id AS source_id FROM credit_note_posting_proposals p JOIN sales_credit_notes c ON c.id=p.credit_note_id JOIN sales_invoices i ON i.id=c.sales_invoice_id WHERE p.board_id=?").bind(boardId).all(),
      ]);
      const data = [...(invoiceRows.results || []), ...(payrollRows.results || []), ...(creditRows.results || [])].sort((a, b) => String(b.created_at || '').localeCompare(String(a.created_at || '')));
      return json({ boardId, view, data });
    }
    const [review, approved, posted] = await Promise.all([
      db.prepare("SELECT (SELECT COUNT(*) FROM posting_proposals WHERE board_id=? AND status='review') + (SELECT COUNT(*) FROM payroll_posting_proposals WHERE board_id=? AND status='review') + (SELECT COUNT(*) FROM credit_note_posting_proposals WHERE board_id=? AND status='review') AS count").bind(boardId, boardId, boardId).first(),
      db.prepare("SELECT (SELECT COUNT(*) FROM posting_proposals WHERE board_id=? AND status='approved') + (SELECT COUNT(*) FROM payroll_posting_proposals WHERE board_id=? AND status='approved') + (SELECT COUNT(*) FROM credit_note_posting_proposals WHERE board_id=? AND status='approved') AS count").bind(boardId, boardId, boardId).first(),
      db.prepare("SELECT (SELECT COUNT(*) FROM posting_proposals WHERE board_id=? AND status='posted') + (SELECT COUNT(*) FROM payroll_posting_proposals WHERE board_id=? AND status='posted') + (SELECT COUNT(*) FROM credit_note_posting_proposals WHERE board_id=? AND status='posted') AS count").bind(boardId, boardId, boardId).first(),
    ]);
    return json({ boardId, view, data: { review, approved, posted, ledgerPosting: 'controlled' } });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};

export const onRequestPost: PagesFunction<Env> = async ({ env, request }) => {
  try {
    const value = await body(request); const boardId = text(value?.boardId, 100); const action = text(value?.action, 60); const db = requireDb(env);
    if (!boardId || !action) return json({ error: 'boardId_and_action_required' }, { status: 400 }); const authorization = await authorizeBoardWrite(request, env, boardId); if (!authorization.allowed) return json({ error: 'write_not_authorized' }, { status: 401 }); const actor = authorization.userId || 'service';
    if (action === 'prepare_sales_invoice' || action === 'prepare_supplier_invoice') {
      const sourceType = action === 'prepare_sales_invoice' ? 'sales_invoice' : 'supplier_invoice'; const sourceId = text(value?.sourceId, 120);
      const source = sourceType === 'sales_invoice'
        ? await db.prepare("SELECT id,invoice_number,issue_date,description,amount_minor,vat_minor,total_minor,status FROM sales_invoices WHERE id=? AND board_id=? AND status='approved'").bind(sourceId, boardId).first<Record<string, unknown>>()
        : await db.prepare("SELECT id,invoice_number,supplier_name,due_date,amount_minor,status,match_status FROM supplier_invoices WHERE id=? AND board_id=? AND status='approved' AND match_status='matched'").bind(sourceId, boardId).first<Record<string, unknown>>();
      if (!source) return json({ error: sourceType === 'sales_invoice' ? 'sales_invoice_not_approved' : 'supplier_invoice_not_approved_or_unmatched' }, { status: 409 });
      const period = text(value?.period, 20) || text(sourceType === 'sales_invoice' ? source.issue_date : source.due_date, 20).slice(0, 7); const voucherDate = text(value?.voucherDate, 20) || text(sourceType === 'sales_invoice' ? source.issue_date : source.due_date, 20);
      if (!periodPattern.test(period) || !datePattern.test(voucherDate)) return json({ error: 'period_or_voucher_date_invalid' }, { status: 400 });
      const invoiceLines = sourceType === 'sales_invoice' ? (await db.prepare('SELECT line_number,description,net_minor,vat_minor,total_minor,vat_code,account_id FROM sales_invoice_lines WHERE board_id=? AND sales_invoice_id=? ORDER BY line_number').bind(boardId, sourceId).all()).results as Record<string, unknown>[] : [];
      if (sourceType === 'sales_invoice' && invoiceLines.length && (invoiceLines.reduce((sum,line)=>sum+Number(line.total_minor||0),0) !== Number(source.total_minor||0) || invoiceLines.reduce((sum,line)=>sum+Number(line.vat_minor||0),0) !== Number(source.vat_minor||0))) return json({error:'sales_invoice_lines_out_of_sync'},{status:409});
      const total = sourceType === 'sales_invoice' ? Number(source.total_minor || 0) : Number(source.amount_minor || 0); const suppliedVat = integerMinor(value?.vatMinor ?? (sourceType === 'sales_invoice' ? source.vat_minor : 0));
      if (!Number.isSafeInteger(total) || total <= 0 || suppliedVat === null || suppliedVat > total) return json({ error: 'amount_or_vat_invalid' }, { status: 400 });
      const net = total - suppliedVat; const accountIds = sourceType === 'sales_invoice' ? [text(value?.receivableAccountId || value?.primaryAccountId, 120), text(value?.revenueAccountId || value?.secondaryAccountId, 120), suppliedVat ? text(value?.vatAccountId, 120) : ''] : [text(value?.expenseAccountId || value?.primaryAccountId, 120), text(value?.payableAccountId || value?.secondaryAccountId, 120), suppliedVat ? text(value?.vatAccountId, 120) : ''];
      const lineAccountIds = invoiceLines.map((line) => text(line.account_id, 120)).filter(Boolean); if (accountIds.some((x, index) => index < 2 && !x) || (suppliedVat && !accountIds[2]) || !(await accountsExist(db, boardId, [...accountIds, ...lineAccountIds]))) return json({ error: 'posting_accounts_invalid' }, { status: 400 });
      const lines: PostingLine[] = sourceType === 'sales_invoice'
        ? [{ accountId: accountIds[0], description: `Kundefordring ${text(source.invoice_number, 80)}`, debitMinor: total, creditMinor: 0 }, ...(invoiceLines.length ? invoiceLines.map((line) => ({ accountId: text(line.account_id, 120) || accountIds[1], description: text(line.description, 200), debitMinor: 0, creditMinor: Number(line.net_minor || 0), vatCode: line.vat_code ? text(line.vat_code, 40) : null })) : [{ accountId: accountIds[1], description: text(source.description, 200), debitMinor: 0, creditMinor: net, vatCode: suppliedVat ? '3' : null }]), ...(suppliedVat ? [{ accountId: accountIds[2], description: `Utgående MVA ${text(source.invoice_number, 80)}`, debitMinor: 0, creditMinor: suppliedVat, vatCode: null }] : [])]
        : [{ accountId: accountIds[0], description: `Kjøp ${text(source.invoice_number, 80)}`, debitMinor: net, creditMinor: 0, vatCode: suppliedVat ? '1' : null }, ...(suppliedVat ? [{ accountId: accountIds[2], description: `Inngående MVA ${text(source.invoice_number, 80)}`, debitMinor: suppliedVat, creditMinor: 0, vatCode: null }] : []), { accountId: accountIds[1], description: `Leverandørgjeld ${text(source.invoice_number, 80)}`, debitMinor: 0, creditMinor: total }];
      const snapshot = JSON.stringify({ sourceType, source, period, voucherDate, suppliedVat, lines }); const proposalId = id('posting'); const sourceHash = await sha256(snapshot);
      try { await db.prepare('INSERT INTO posting_proposals (id,board_id,source_type,source_id,period,voucher_date,description,amount_minor,lines_json,source_snapshot,source_hash,status,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,\'review\',?)').bind(proposalId, boardId, sourceType, sourceId, period, voucherDate, sourceType === 'sales_invoice' ? `Faktura ${text(source.invoice_number, 80)}` : `Leverandørfaktura ${text(source.invoice_number, 80)}`, total, JSON.stringify(lines), snapshot, sourceHash, actor).run(); } catch (error) { if (error instanceof Error && error.message.includes('UNIQUE')) return json({ error: 'posting_proposal_exists' }, { status: 409 }); throw error; }
      await recordAudit(db, { boardId, action: 'posting_proposal_prepared', entityType: 'posting_proposal', entityId: proposalId, userId: authorization.userId || undefined, details: { sourceType, sourceId, period, amountMinor: total, vatMinor: suppliedVat, requiresHumanApproval: true } }); return json({ ok: true, action, proposalId, sourceType, sourceId, period, status: 'review', amountMinor: total, vatMinor: suppliedVat, requiresHumanApproval: true }, { status: 201 });
    }
    if (action === 'prepare_credit_note') {
      const sourceId=text(value?.sourceId,120); const source=await db.prepare("SELECT c.*,i.invoice_number FROM sales_credit_notes c JOIN sales_invoices i ON i.id=c.sales_invoice_id WHERE c.id=? AND c.board_id=? AND c.status='approved' AND c.posted_voucher_id IS NULL").bind(sourceId,boardId).first<Record<string,unknown>>(); if(!source)return json({error:'credit_note_not_approved_or_already_posted'},{status:409}); const period=text(value?.period,20)||text(source.issue_date,20).slice(0,7),voucherDate=text(source.issue_date,20); if(!periodPattern.test(period)||!datePattern.test(voucherDate))return json({error:'period_or_voucher_date_invalid'},{status:400}); const total=Number(source.total_minor||0),vat=Number(source.vat_minor||0),net=Number(source.amount_minor||0); if(total<=0||net+vat!==total)return json({error:'credit_note_amount_invalid'},{status:409}); const receivable=text(value?.receivableAccountId||value?.primaryAccountId,120),revenue=text(value?.revenueAccountId||value?.secondaryAccountId,120),vatAccount=vat?text(value?.vatAccountId,120):''; const accountIds=[receivable,revenue,...(vat?[vatAccount]:[])]; if(accountIds.some(x=>!x)||!(await accountsExist(db,boardId,accountIds)))return json({error:'posting_accounts_invalid'},{status:400}); const lines:PostingLine[]=[{accountId:revenue,description:`Kreditnota ${text(source.credit_note_number,80)}`,debitMinor:net,creditMinor:0,vatCode:vat?'3C':null},...(vat?[{accountId:vatAccount,description:`Reversert utgående MVA ${text(source.credit_note_number,80)}`,debitMinor:vat,creditMinor:0,vatCode:null}]:[]),{accountId:receivable,description:`Redusert kundefordring ${text(source.invoice_number,80)}`,debitMinor:0,creditMinor:total}]; const snapshot=JSON.stringify({sourceType:'sales_credit_note',source,period,voucherDate,lines}); const proposalId=id('creditposting'),sourceHash=await sha256(snapshot); try{await db.prepare("INSERT INTO credit_note_posting_proposals (id,board_id,credit_note_id,period,voucher_date,description,amount_minor,lines_json,source_snapshot,source_hash,status,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,'review',?)").bind(proposalId,boardId,sourceId,period,voucherDate,`Kreditnota ${text(source.credit_note_number,80)}`,total,JSON.stringify(lines),snapshot,sourceHash,actor).run();}catch(error){if(error instanceof Error&&error.message.includes('UNIQUE'))return json({error:'posting_proposal_exists'},{status:409});throw error;} await recordAudit(db,{boardId,action:'credit_note_posting_prepared',entityType:'credit_note_posting_proposal',entityId:proposalId,userId:authorization.userId||undefined,details:{creditNoteId:sourceId,period,total,vat,requiresHumanApproval:true}}); return json({ok:true,action,proposalId,sourceType:'sales_credit_note',sourceId,period,status:'review',amountMinor:total,requiresHumanApproval:true},{status:201});
    }
    if (action === 'prepare_payroll') {
      const sourceId = text(value?.sourceId, 120);
      const source = await db.prepare("SELECT r.*, c.status AS compliance_status, c.holiday_pay_minor AS checked_holiday_pay_minor, c.otp_minor AS checked_otp_minor FROM payroll_runs r JOIN payroll_compliance_checks c ON c.payroll_run_id=r.id AND c.board_id=r.board_id WHERE r.id=? AND r.board_id=? AND r.status='approved' AND c.status='approved'").bind(sourceId, boardId).first<Record<string, unknown>>();
      if (!source) return json({ error: 'payroll_run_or_compliance_not_approved' }, { status: 409 });
      const period = text(value?.period, 20) || text(source.period, 20); const voucherDate = text(value?.voucherDate, 20) || `${period}-01`;
      if (!periodPattern.test(period) || !datePattern.test(voucherDate)) return json({ error: 'period_or_voucher_date_invalid' }, { status: 400 });
      const gross = integerMinor(source.gross_minor); const tax = integerMinor(source.tax_withheld_minor); const employer = integerMinor(source.employer_cost_minor);
      const salaryAccount = text(value?.salaryExpenseAccountId || value?.primaryAccountId, 120); const taxAccount = text(value?.taxLiabilityAccountId, 120); const payableAccount = text(value?.payrollPayableAccountId || value?.secondaryAccountId, 120); const employerExpenseAccount = text(value?.employerCostAccountId, 120); const employerLiabilityAccount = text(value?.employerLiabilityAccountId, 120);
      const employerContribution = employer !== null && gross !== null ? employer - gross : 0;
      const requiredAccounts = [salaryAccount, taxAccount, payableAccount, ...(employerContribution ? [employerExpenseAccount, employerLiabilityAccount] : [])];
      if (gross === null || tax === null || employer === null || gross <= 0 || tax > gross || employer < gross || requiredAccounts.some((account) => !account) || !(await accountsExist(db, boardId, requiredAccounts))) return json({ error: 'payroll_posting_fields_invalid' }, { status: 400 });
      const netPay = gross - tax;
      const lines: PostingLine[] = [{ accountId: salaryAccount, description: `Lønn ${text(source.period, 20)}`, debitMinor: gross, creditMinor: 0 }, ...(employerContribution ? [{ accountId: employerExpenseAccount, description: `Arbeidsgiverkostnad ${text(source.period, 20)}`, debitMinor: employerContribution, creditMinor: 0 }] : []), { accountId: taxAccount, description: `Forskuddstrekk ${text(source.period, 20)}`, debitMinor: 0, creditMinor: tax }, { accountId: payableAccount, description: `Skyldig lønn ${text(source.period, 20)}`, debitMinor: 0, creditMinor: netPay }, ...(employerContribution ? [{ accountId: employerLiabilityAccount, description: `Skyldig arbeidsgiverkostnad ${text(source.period, 20)}`, debitMinor: 0, creditMinor: employerContribution }] : [])];
      const snapshot = JSON.stringify({ sourceType: 'payroll_run', source, period, voucherDate, lines }); const proposalId = id('payposting'); const sourceHash = await sha256(snapshot);
      try { await db.prepare('INSERT INTO payroll_posting_proposals (id,board_id,payroll_run_id,period,voucher_date,description,amount_minor,lines_json,source_snapshot,source_hash,status,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,\'review\',?)').bind(proposalId, boardId, sourceId, period, voucherDate, `Lønn ${text(source.period, 20)}`, employer, JSON.stringify(lines), snapshot, sourceHash, actor).run(); } catch (error) { if (error instanceof Error && error.message.includes('UNIQUE')) return json({ error: 'posting_proposal_exists' }, { status: 409 }); throw error; }
      await recordAudit(db, { boardId, action: 'payroll_posting_proposal_prepared', entityType: 'payroll_posting_proposal', entityId: proposalId, userId: authorization.userId || undefined, details: { payrollRunId: sourceId, period, amountMinor: employer, requiresHumanApproval: true } }); return json({ ok: true, action, proposalId, sourceType: 'payroll_run', sourceId, period, status: 'review', amountMinor: employer, requiresHumanApproval: true }, { status: 201 });
    }
    if (action === 'approve_proposal') { const proposalId = text(value?.proposalId, 120); const result = await db.prepare("UPDATE posting_proposals SET status='approved',approved_by=?,approved_at=datetime('now'),updated_at=datetime('now') WHERE id=? AND board_id=? AND status='review'").bind(actor, proposalId, boardId).run(); if (!result.meta?.changes) return json({ error: 'proposal_not_in_review_or_found' }, { status: 409 }); await recordAudit(db, { boardId, action: 'posting_proposal_approved', entityType: 'posting_proposal', entityId: proposalId, userId: authorization.userId || undefined, details: { requiresHumanApproval: false } }); return json({ ok: true, action, proposalId, status: 'approved' }); }
    if (action === 'approve_payroll_proposal') { const proposalId = text(value?.proposalId, 120); const result = await db.prepare("UPDATE payroll_posting_proposals SET status='approved',approved_by=?,approved_at=datetime('now'),updated_at=datetime('now') WHERE id=? AND board_id=? AND status='review'").bind(actor, proposalId, boardId).run(); if (!result.meta?.changes) return json({ error: 'payroll_proposal_not_in_review_or_found' }, { status: 409 }); await recordAudit(db, { boardId, action: 'payroll_posting_proposal_approved', entityType: 'payroll_posting_proposal', entityId: proposalId, userId: authorization.userId || undefined, details: { requiresHumanApproval: false } }); return json({ ok: true, action, proposalId, status: 'approved' }); }
    if (action === 'approve_credit_note_proposal') { const proposalId=text(value?.proposalId,120); const result=await db.prepare("UPDATE credit_note_posting_proposals SET status='approved',approved_by=?,approved_at=datetime('now'),updated_at=datetime('now') WHERE id=? AND board_id=? AND status='review'").bind(actor,proposalId,boardId).run(); if(!result.meta?.changes)return json({error:'credit_note_proposal_not_in_review_or_found'},{status:409}); return json({ok:true,action,proposalId,status:'approved'}); }
    if (action === 'post_proposal') {
      const proposalId = text(value?.proposalId, 120); const proposal = await db.prepare("SELECT * FROM posting_proposals WHERE id=? AND board_id=? AND status='approved'").bind(proposalId, boardId).first<Record<string, unknown>>(); if (!proposal) return json({ error: 'proposal_not_approved_or_found' }, { status: 409 });
      if (await db.prepare("SELECT 1 FROM accounting_periods WHERE board_id=? AND period=? AND status='locked'").bind(boardId, proposal.period).first()) return json({ error: 'period_locked', period: proposal.period }, { status: 409 });
      const lines = JSON.parse(String(proposal.lines_json || '[]')) as PostingLine[]; if (!lines.length || !(await accountsExist(db, boardId, lines.map((line) => line.accountId)))) return json({ error: 'posting_lines_invalid' }, { status: 400 });
      const posted = await nextVoucher(db, boardId, { voucherDate: String(proposal.voucher_date), period: String(proposal.period), description: String(proposal.description), source: `posting:${proposal.source_type}`, externalReference: `${proposal.source_type}:${proposal.source_id}`, createdBy: actor }, lines);
      await db.prepare("UPDATE posting_proposals SET status='posted',voucher_id=?,posted_by=?,posted_at=datetime('now'),updated_at=datetime('now') WHERE id=? AND board_id=? AND status='approved'").bind(posted.voucherId, actor, proposalId, boardId).run(); await recordAudit(db, { boardId, action: 'posting_proposal_posted', entityType: 'posting_proposal', entityId: proposalId, userId: authorization.userId || undefined, details: { voucherId: posted.voucherId, voucherNumber: posted.voucherNumber, period: proposal.period, sourceType: proposal.source_type, sourceId: proposal.source_id } }); return json({ ok: true, action, proposalId, status: 'posted', voucherId: posted.voucherId, voucherNumber: posted.voucherNumber, period: proposal.period }, { status: 201 });
    }
    if (action === 'post_payroll_proposal') {
      const proposalId = text(value?.proposalId, 120); const proposal = await db.prepare("SELECT * FROM payroll_posting_proposals WHERE id=? AND board_id=? AND status='approved'").bind(proposalId, boardId).first<Record<string, unknown>>(); if (!proposal) return json({ error: 'payroll_proposal_not_approved_or_found' }, { status: 409 });
      if (await db.prepare("SELECT 1 FROM accounting_periods WHERE board_id=? AND period=? AND status='locked'").bind(boardId, proposal.period).first()) return json({ error: 'period_locked', period: proposal.period }, { status: 409 });
      const lines = JSON.parse(String(proposal.lines_json || '[]')) as PostingLine[]; if (!lines.length || !(await accountsExist(db, boardId, lines.map((line) => line.accountId)))) return json({ error: 'posting_lines_invalid' }, { status: 400 });
      const posted = await nextVoucher(db, boardId, { voucherDate: String(proposal.voucher_date), period: String(proposal.period), description: String(proposal.description), source: 'posting:payroll_run', externalReference: `payroll_run:${proposal.payroll_run_id}`, createdBy: actor }, lines);
      await db.prepare("UPDATE payroll_posting_proposals SET status='posted',voucher_id=?,posted_by=?,posted_at=datetime('now'),updated_at=datetime('now') WHERE id=? AND board_id=? AND status='approved'").bind(posted.voucherId, actor, proposalId, boardId).run(); await recordAudit(db, { boardId, action: 'payroll_posting_proposal_posted', entityType: 'payroll_posting_proposal', entityId: proposalId, userId: authorization.userId || undefined, details: { voucherId: posted.voucherId, voucherNumber: posted.voucherNumber, period: proposal.period, payrollRunId: proposal.payroll_run_id } }); return json({ ok: true, action, proposalId, status: 'posted', voucherId: posted.voucherId, voucherNumber: posted.voucherNumber, period: proposal.period }, { status: 201 });
    }
    if (action === 'post_credit_note_proposal') { const proposalId=text(value?.proposalId,120); const proposal=await db.prepare("SELECT p.*,c.sales_invoice_id FROM credit_note_posting_proposals p JOIN sales_credit_notes c ON c.id=p.credit_note_id WHERE p.id=? AND p.board_id=? AND p.status='approved'").bind(proposalId,boardId).first<Record<string,unknown>>(); if(!proposal)return json({error:'credit_note_proposal_not_approved_or_found'},{status:409}); if(await db.prepare("SELECT 1 FROM accounting_periods WHERE board_id=? AND period=? AND status='locked'").bind(boardId,proposal.period).first())return json({error:'period_locked',period:proposal.period},{status:409}); const lines=JSON.parse(String(proposal.lines_json||'[]')) as PostingLine[]; if(!lines.length||!(await accountsExist(db,boardId,lines.map(x=>x.accountId))))return json({error:'posting_lines_invalid'},{status:400}); const posted=await nextVoucher(db,boardId,{voucherDate:String(proposal.voucher_date),period:String(proposal.period),description:String(proposal.description),source:'posting:sales_credit_note',externalReference:`sales_credit_note:${proposal.credit_note_id}`,createdBy:actor},lines); await db.batch([db.prepare("UPDATE credit_note_posting_proposals SET status='posted',voucher_id=?,posted_by=?,posted_at=datetime('now'),updated_at=datetime('now') WHERE id=? AND board_id=? AND status='approved'").bind(posted.voucherId,actor,proposalId,boardId),db.prepare("UPDATE sales_credit_notes SET status='posted',posted_voucher_id=? WHERE id=? AND board_id=? AND status='approved'").bind(posted.voucherId,proposal.credit_note_id,boardId)]); await recordAudit(db,{boardId,action:'credit_note_posting_posted',entityType:'credit_note_posting_proposal',entityId:proposalId,userId:authorization.userId||undefined,details:{voucherId:posted.voucherId,voucherNumber:posted.voucherNumber,creditNoteId:proposal.credit_note_id}}); return json({ok:true,action,proposalId,status:'posted',voucherId:posted.voucherId,voucherNumber:posted.voucherNumber,period:proposal.period},{status:201}); }
    return json({ error: 'unknown_action', allowed: ['prepare_sales_invoice', 'prepare_supplier_invoice', 'prepare_credit_note', 'prepare_payroll', 'approve_proposal', 'approve_payroll_proposal', 'approve_credit_note_proposal', 'post_proposal', 'post_payroll_proposal', 'post_credit_note_proposal'] }, { status: 400 });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};
