import { authorizeBoardRead, authorizeBoardWrite, body, json, recordAudit, requireDb, type Env } from './_lib';

const views = new Set(['summary', 'orders', 'receipts', 'invoices', 'invoice-lines', 'ehf']);
const actions = ['create_order', 'approve_order', 'create_receipt', 'create_invoice', 'match_invoice', 'attest_invoice', 'assign_invoice', 'record_invoice_payment', 'receive_ehf', 'validate_ehf', 'link_ehf_invoice'];
const txt = (v: unknown, max = 200) => String(v ?? '').trim().slice(0, max);
const num = (v: unknown) => Number.isFinite(Number(v)) && Number(v) >= 0 ? Math.round(Number(v)) : null;
const isoDate = (v: unknown) => /^\d{4}-\d{2}-\d{2}$/.test(String(v ?? '')) ? String(v) : null;
const newId = (p: string) => `${p}-${crypto.randomUUID()}`;

export const onRequestGet: PagesFunction<Env> = async ({ env, request }) => {
  const u = new URL(request.url); const boardId = txt(u.searchParams.get('boardId')); const view = u.searchParams.get('view') || 'summary'; const invoiceId = txt(u.searchParams.get('invoiceId'));
  if (!boardId) return json({ error: 'boardId_required' }, { status: 400 }); if (!views.has(view)) return json({ error: 'unknown_view', allowed: [...views] }, { status: 400 });
  if (!(await authorizeBoardRead(request, env, boardId))) return json({ error: 'board_access_denied' }, { status: 403 });
  try {
    const db = requireDb(env); const q: Record<string, string> = { orders: 'SELECT * FROM purchase_orders WHERE board_id=? ORDER BY created_at DESC', receipts: 'SELECT r.*,o.order_number,o.supplier_name FROM goods_receipts r JOIN purchase_orders o ON o.id=r.purchase_order_id WHERE r.board_id=? ORDER BY r.received_date DESC', invoices: 'SELECT i.*,o.order_number,(SELECT COUNT(*) FROM supplier_invoice_lines l WHERE l.supplier_invoice_id=i.id) AS line_count FROM supplier_invoices i LEFT JOIN purchase_orders o ON o.id=i.purchase_order_id WHERE i.board_id=? ORDER BY i.due_date', 'invoice-lines': 'SELECT * FROM supplier_invoice_lines WHERE board_id=? AND supplier_invoice_id=? ORDER BY line_number', ehf: 'SELECT e.*,i.status invoice_status FROM ehf_documents e LEFT JOIN supplier_invoices i ON i.id=e.supplier_invoice_id WHERE e.board_id=? ORDER BY e.created_at DESC' };
    if (view !== 'summary') {
      if (view === 'invoice-lines' && !invoiceId) return json({ error: 'invoiceId_required' }, { status: 400 });
      return json({ boardId, view, data: (await db.prepare(q[view]).bind(...(view === 'invoice-lines' ? [boardId, invoiceId] : [boardId])).all()).results });
    }
    const [orders, receipts, invoices, exceptions, ehf] = await Promise.all([db.prepare("SELECT COUNT(*) count,COALESCE(SUM(total_minor),0) total_minor FROM purchase_orders WHERE board_id=? AND status NOT IN ('closed','cancelled')").bind(boardId).first(), db.prepare("SELECT COUNT(*) count FROM goods_receipts WHERE board_id=? AND status='confirmed'").bind(boardId).first(), db.prepare("SELECT COUNT(*) count,COALESCE(SUM(MAX(0,amount_minor-paid_minor)),0) amount_minor FROM supplier_invoices WHERE board_id=? AND status NOT IN ('paid','cancelled') AND amount_minor>paid_minor").bind(boardId).first(), db.prepare("SELECT COUNT(*) count FROM supplier_invoices WHERE board_id=? AND match_status='exception'").bind(boardId).first(), db.prepare("SELECT COUNT(*) count FROM ehf_documents WHERE board_id=? AND status IN ('received','validated')").bind(boardId).first()]);
    return json({ boardId, view, data: { orders, receipts, invoices, exceptions, ehf, transport: 'not_configured' } });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};

export const onRequestPost: PagesFunction<Env> = async ({ env, request }) => {
  try {
    const v = await body(request); const boardId = txt(v?.boardId); const action = txt(v?.action, 40); const db = requireDb(env);
    if (!boardId || !action) return json({ error: 'boardId_and_action_required' }, { status: 400 }); if (!actions.includes(action)) return json({ error: 'unknown_action', allowed: actions }, { status: 400 });
    const auth = await authorizeBoardWrite(request, env, boardId); if (!auth.allowed) return json({ error: 'write_not_authorized' }, { status: 401 }); const actor = auth.userId || 'api';
    if (action === 'create_order') {
      const orderNumber = txt(v?.orderNumber, 60), supplierName = txt(v?.supplierName), totalMinor = num(v?.totalMinor), currency = txt(v?.currency, 3).toUpperCase(); if (!orderNumber || !supplierName || totalMinor === null || !/^[A-Z]{3}$/.test(currency)) return json({ error: 'order_fields_invalid' }, { status: 400 });
      const orderId = newId('po'); await db.prepare("INSERT INTO purchase_orders (id,board_id,order_number,supplier_name,status,total_minor,currency,requested_by,created_at) VALUES (?,?,?,?,?,?,?,?,datetime('now'))").bind(orderId, boardId, orderNumber, supplierName, 'pending_approval', totalMinor, currency, actor).run(); await recordAudit(db, { boardId, action: 'purchase_order_created', entityType: 'purchase_order', entityId: orderId, userId: auth.userId || undefined, details: { status: 'pending_approval' } }); return json({ ok: true, action, orderId, status: 'pending_approval' }, { status: 201 });
    }
    if (action === 'approve_order') {
      const orderId = txt(v?.orderId, 100), result = await db.prepare("UPDATE purchase_orders SET status='approved',approved_by=?,approved_at=datetime('now') WHERE id=? AND board_id=? AND status='pending_approval'").bind(txt(v?.approvedBy, 120) || actor, orderId, boardId).run(); if (!result.meta?.changes) return json({ error: 'order_not_pending_or_found' }, { status: 409 }); await recordAudit(db, { boardId, action: 'purchase_order_approved', entityType: 'purchase_order', entityId: orderId, userId: auth.userId || undefined, details: { externalOrdering: 'not_configured' } }); return json({ ok: true, action, orderId, status: 'approved', externalOrdering: 'not_configured' });
    }
    if (action === 'create_receipt') {
      const purchaseOrderId = txt(v?.purchaseOrderId, 100), receivedDate = isoDate(v?.receivedDate), receiptStatus = ['draft', 'confirmed', 'disputed'].includes(txt(v?.status, 20)) ? txt(v?.status, 20) : 'draft'; if (!purchaseOrderId || !receivedDate) return json({ error: 'receipt_fields_invalid' }, { status: 400 }); if (!(await db.prepare('SELECT id FROM purchase_orders WHERE id=? AND board_id=?').bind(purchaseOrderId, boardId).first())) return json({ error: 'purchase_order_not_found' }, { status: 404 });
      const receiptId = newId('gr'); await db.prepare("INSERT INTO goods_receipts (id,board_id,purchase_order_id,received_date,received_by,status,notes,created_at) VALUES (?,?,?,?,?,?,?,datetime('now'))").bind(receiptId, boardId, purchaseOrderId, receivedDate, actor, receiptStatus, txt(v?.notes, 500)).run(); await recordAudit(db, { boardId, action: 'goods_receipt_created', entityType: 'goods_receipt', entityId: receiptId, userId: auth.userId || undefined, details: { status: receiptStatus } }); return json({ ok: true, action, receiptId, status: receiptStatus }, { status: 201 });
    }
    if (action === 'create_invoice') {
      const invoiceNumber = txt(v?.invoiceNumber, 80), supplierName = txt(v?.supplierName), currency = txt(v?.currency, 3).toUpperCase(), dueDate = isoDate(v?.dueDate), purchaseOrderId = txt(v?.purchaseOrderId, 100) || null;
      const rawLines = Array.isArray(v?.lines) ? v.lines : [];
      const lines = rawLines.length ? rawLines : [{ description: txt(v?.description, 200) || 'Leverandørkjøp', quantity: 1, unitPriceMinor: num(v?.amountMinor), vatRate: 0, accountId: txt(v?.accountId, 120) || null }];
      if (!invoiceNumber || !supplierName || !dueDate || !/^[A-Z]{3}$/.test(currency) || lines.length > 100) return json({ error: 'invoice_fields_invalid' }, { status: 400 });
      const normalized: Array<Record<string, unknown>> = [];
      for (let index = 0; index < lines.length; index += 1) {
        const line = lines[index] || {}; const description = txt(line.description, 200); const quantity = Number(line.quantity); const unitPriceMinor = num(line.unitPriceMinor); const vatRate = Number(line.vatRate);
        if (!description || !Number.isFinite(quantity) || quantity <= 0 || quantity > 100000 || unitPriceMinor === null || unitPriceMinor < 0 || ![0,15,25].includes(vatRate)) return json({ error: 'invoice_line_invalid', line: index + 1 }, { status: 400 });
        const netMinor = Math.round(quantity * unitPriceMinor); const vatMinor = Math.round(netMinor * vatRate / 100); normalized.push({ lineNumber: index + 1, description, quantity, unitPriceMinor, vatRate, vatCode: vatRate === 15 ? '1_15' : vatRate === 25 ? '1' : null, netMinor, vatMinor, totalMinor: netMinor + vatMinor, accountId: txt(line.accountId, 120) || null });
      }
      const amountMinor = normalized.reduce((sum, line) => sum + Number(line.totalMinor), 0); const vatMinor = normalized.reduce((sum, line) => sum + Number(line.vatMinor), 0);
      if (amountMinor <= 0) return json({ error: 'invoice_amount_invalid' }, { status: 400 }); if (purchaseOrderId && !(await db.prepare('SELECT id FROM purchase_orders WHERE id=? AND board_id=?').bind(purchaseOrderId, boardId).first())) return json({ error: 'purchase_order_not_found' }, { status: 404 });
      const invoiceId = newId('si'); const statements = [db.prepare("INSERT INTO supplier_invoices (id,board_id,purchase_order_id,invoice_number,supplier_name,amount_minor,vat_minor,currency,due_date,status,match_status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,datetime('now'))").bind(invoiceId, boardId, purchaseOrderId, invoiceNumber, supplierName, amountMinor, vatMinor, currency, dueDate, 'received', 'unmatched')];
      for (const line of normalized) statements.push(db.prepare('INSERT INTO supplier_invoice_lines (id,board_id,supplier_invoice_id,line_number,description,quantity,unit_price_minor,vat_rate,vat_code,net_minor,vat_minor,total_minor,account_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(newId('sil'), boardId, invoiceId, line.lineNumber, line.description, line.quantity, line.unitPriceMinor, line.vatRate, line.vatCode, line.netMinor, line.vatMinor, line.totalMinor, line.accountId));
      await db.batch(statements); await recordAudit(db, { boardId, action: 'supplier_invoice_created', entityType: 'supplier_invoice', entityId: invoiceId, userId: auth.userId || undefined, details: { purchaseOrderId, lineCount: normalized.length, amountMinor, vatMinor } }); return json({ ok: true, action, invoiceId, status: 'received', matchStatus: 'unmatched', amountMinor, vatMinor, lineCount: normalized.length }, { status: 201 });
    }
    if (action === 'receive_ehf') {
      const documentRef = txt(v?.documentRef, 120), supplierName = txt(v?.supplierName), invoiceNumber = txt(v?.invoiceNumber, 80), issueDate = isoDate(v?.issueDate), dueDate = isoDate(v?.dueDate), currency = txt(v?.currency, 3).toUpperCase();
      const rawLines = Array.isArray(v?.lines) ? v.lines : []; const lines = rawLines.length ? rawLines : [{ description: 'EHF-kjøp', quantity: 1, unitPriceMinor: num(v?.amountMinor), vatRate: 0 }]; const normalized: Array<Record<string, unknown>> = [];
      for (let index = 0; index < lines.length; index += 1) { const line = lines[index] || {}; const description = txt(line.description, 200), quantity = Number(line.quantity), unitPriceMinor = num(line.unitPriceMinor), vatRate = Number(line.vatRate); if (!description || !Number.isFinite(quantity) || quantity <= 0 || unitPriceMinor === null || ![0,15,25].includes(vatRate)) return json({ error: 'ehf_line_invalid', line: index + 1 }, { status: 400 }); const netMinor = Math.round(quantity * unitPriceMinor); const vatMinor = Math.round(netMinor * vatRate / 100); normalized.push({ lineNumber: index + 1, description, quantity, unitPriceMinor, vatRate, vatCode: vatRate === 15 ? '1_15' : vatRate === 25 ? '1' : null, netMinor, vatMinor, totalMinor: netMinor + vatMinor, accountId: txt(line.accountId, 120) || null }); }
      const amountMinor = normalized.reduce((sum, line) => sum + Number(line.totalMinor), 0), vatMinor = normalized.reduce((sum, line) => sum + Number(line.vatMinor), 0);
      if (!documentRef || !supplierName || !invoiceNumber || !issueDate || !dueDate || amountMinor <= 0 || !/^[A-Z]{3}$/.test(currency) || normalized.length > 100) return json({ error: 'ehf_fields_invalid', required: ['documentRef','supplierName','invoiceNumber','issueDate','dueDate','lines','currency'] }, { status: 400 });
      const ehfId = newId('ehf'); const statements = [db.prepare("INSERT INTO ehf_documents (id,board_id,document_ref,standard,profile,supplier_name,supplier_org_number,invoice_number,issue_date,due_date,amount_minor,vat_minor,currency,source,status,external_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'received','not_configured')").bind(ehfId, boardId, documentRef, txt(v?.standard, 40) || 'EHF 3.0', txt(v?.profile, 160) || null, supplierName, txt(v?.supplierOrgNumber, 30) || null, invoiceNumber, issueDate, dueDate, amountMinor, vatMinor, currency, ['manual','upload','peppol'].includes(txt(v?.source, 20)) ? txt(v?.source, 20) : 'manual')];
      for (const line of normalized) statements.push(db.prepare('INSERT INTO ehf_document_lines (id,board_id,ehf_document_id,line_number,description,quantity,unit_price_minor,vat_rate,vat_code,net_minor,vat_minor,total_minor,account_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(newId('ehfl'), boardId, ehfId, line.lineNumber, line.description, line.quantity, line.unitPriceMinor, line.vatRate, line.vatCode, line.netMinor, line.vatMinor, line.totalMinor, line.accountId)); await db.batch(statements); await recordAudit(db, { boardId, action: 'ehf_document_received', entityType: 'ehf_document', entityId: ehfId, userId: auth.userId || undefined, details: { source: txt(v?.source, 20) || 'manual', transport: 'not_configured', lineCount: normalized.length, amountMinor, vatMinor } }); return json({ ok: true, action, ehfId, status: 'received', amountMinor, vatMinor, lineCount: normalized.length, transport: 'not_configured' }, { status: 201 });
    }
    if (action === 'validate_ehf') {
      const ehfId = txt(v?.ehfId, 100); const document = await db.prepare("SELECT * FROM ehf_documents WHERE id=? AND board_id=? AND status IN ('received','rejected')").bind(ehfId, boardId).first<Record<string, unknown>>(); if (!document) return json({ error: 'ehf_not_received_or_found' }, { status: 409 });
      const errors: string[] = []; if (!txt(document.supplier_name)) errors.push('supplier_name_missing'); if (!txt(document.invoice_number)) errors.push('invoice_number_missing'); if (!isoDate(document.issue_date)) errors.push('issue_date_invalid'); if (!isoDate(document.due_date)) errors.push('due_date_invalid'); if (Number(document.amount_minor || 0) <= 0) errors.push('amount_invalid'); if (!/^[A-Z]{3}$/.test(txt(document.currency, 3))) errors.push('currency_invalid'); const status = errors.length ? 'rejected' : 'validated'; await db.prepare('UPDATE ehf_documents SET status=?,validation_errors=?,validated_at=datetime(\'now\') WHERE id=? AND board_id=?').bind(status, errors.length ? JSON.stringify(errors) : null, ehfId, boardId).run(); await recordAudit(db, { boardId, action: 'ehf_document_validated', entityType: 'ehf_document', entityId: ehfId, userId: auth.userId || undefined, details: { status, errors, transport: 'not_configured' } }); return json({ ok: !errors.length, action, ehfId, status, errors, requiresHumanReview: true });
    }
    if (action === 'link_ehf_invoice') {
      const ehfId = txt(v?.ehfId, 100); const document = await db.prepare("SELECT * FROM ehf_documents WHERE id=? AND board_id=? AND status='validated' AND supplier_invoice_id IS NULL").bind(ehfId, boardId).first<Record<string, unknown>>(); if (!document) return json({ error: 'ehf_not_validated_or_already_linked' }, { status: 409 });
      const invoiceId = newId('si'); const ehfLines = (await db.prepare('SELECT * FROM ehf_document_lines WHERE board_id=? AND ehf_document_id=? ORDER BY line_number').bind(boardId, ehfId).all()).results as Record<string, unknown>[]; const statements = [db.prepare("INSERT INTO supplier_invoices (id,board_id,invoice_number,supplier_name,amount_minor,vat_minor,currency,due_date,status,match_status,external_reference,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,datetime('now'))").bind(invoiceId, boardId, txt(document.invoice_number, 80), txt(document.supplier_name), Number(document.amount_minor), Number(document.vat_minor || 0), txt(document.currency, 3), txt(document.due_date, 20), 'received', 'unmatched', `EHF:${txt(document.document_ref, 120)}`)]; for (const line of ehfLines) statements.push(db.prepare('INSERT INTO supplier_invoice_lines (id,board_id,supplier_invoice_id,line_number,description,quantity,unit_price_minor,vat_rate,vat_code,net_minor,vat_minor,total_minor,account_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(newId('sil'), boardId, invoiceId, line.line_number, line.description, line.quantity, line.unit_price_minor, line.vat_rate, line.vat_code, line.net_minor, line.vat_minor, line.total_minor, line.account_id)); await db.batch(statements); await db.prepare("UPDATE ehf_documents SET status='linked',supplier_invoice_id=? WHERE id=? AND board_id=?").bind(invoiceId, ehfId, boardId).run(); await recordAudit(db, { boardId, action: 'ehf_document_linked_to_invoice', entityType: 'ehf_document', entityId: ehfId, userId: auth.userId || undefined, details: { supplierInvoiceId: invoiceId, lineCount: ehfLines.length, nextStep: 'three_way_match' } }); return json({ ok: true, action, ehfId, supplierInvoiceId: invoiceId, status: 'linked', lineCount: ehfLines.length, nextStep: 'three_way_match' }, { status: 201 });
    }
    if (action === 'match_invoice') {
      const invoiceId = txt(v?.invoiceId, 100); const invoice = await db.prepare("SELECT i.id,i.purchase_order_id,o.id order_id FROM supplier_invoices i LEFT JOIN purchase_orders o ON o.id=i.purchase_order_id WHERE i.id=? AND i.board_id=? AND i.status='received'").bind(invoiceId, boardId).first() as { id?: string; purchase_order_id?: string; order_id?: string } | null; if (!invoice) return json({ error: 'invoice_not_received_or_found' }, { status: 409 });
      if (!invoice.purchase_order_id || !invoice.order_id || !(await db.prepare("SELECT id FROM goods_receipts WHERE board_id=? AND purchase_order_id=? AND status='confirmed'").bind(boardId, invoice.purchase_order_id).first())) { await db.prepare("UPDATE supplier_invoices SET match_status='exception',status='exception' WHERE id=? AND board_id=?").bind(invoiceId, boardId).run(); return json({ error: 'three_way_match_required', invoiceId, status: 'exception' }, { status: 409 }); }
      await db.prepare("UPDATE supplier_invoices SET match_status='matched',status='matched' WHERE id=? AND board_id=? AND status='received'").bind(invoiceId, boardId).run(); await recordAudit(db, { boardId, action: 'supplier_invoice_matched', entityType: 'supplier_invoice', entityId: invoiceId, userId: auth.userId || undefined, details: { requiresHumanApproval: true, threeWayMatch: true } }); return json({ ok: true, action, invoiceId, status: 'matched', requiresHumanApproval: true });
    }
    if (action === 'attest_invoice') {
      const invoiceId = txt(v?.invoiceId, 100); const result = await db.prepare("UPDATE supplier_invoices SET attested_by=?,attested_at=datetime('now') WHERE id=? AND board_id=? AND status='matched' AND match_status='matched' AND attested_at IS NULL").bind(actor, invoiceId, boardId).run(); if (!result.meta?.changes) return json({ error: 'invoice_not_ready_for_attestation' }, { status: 409 }); await recordAudit(db, { boardId, action: 'supplier_invoice_attested', entityType: 'supplier_invoice', entityId: invoiceId, userId: auth.userId || undefined, details: { nextStep: 'anvisning', externalPayment: 'not_configured' } }); return json({ ok: true, action, invoiceId, status: 'matched', approvalStage: 'attested', nextStep: 'assign_invoice', payment: 'not_configured' });
    }
    if (action === 'record_invoice_payment') {
      const invoiceId = txt(v?.invoiceId, 100), paymentReference = txt(v?.paymentReference, 120); const requestedAmount = v?.amountMinor === undefined || v?.amountMinor === '' ? null : Number(v?.amountMinor); if (!paymentReference) return json({ error: 'payment_reference_required' }, { status: 400 }); if (requestedAmount !== null && (!Number.isSafeInteger(requestedAmount) || requestedAmount <= 0)) return json({ error: 'payment_amount_invalid' }, { status: 400 });
      const invoice=await db.prepare("SELECT amount_minor,paid_minor,status FROM supplier_invoices WHERE id=? AND board_id=?").bind(invoiceId,boardId).first<Record<string,unknown>>(); if(!invoice)return json({error:'supplier_invoice_not_payable_or_found',detail:'Fakturaen må være attestert og anvist før betaling kan registreres.'},{status:409});
      const total=Number(invoice.amount_minor||0),alreadyPaid=Number(invoice.paid_minor||0),remaining=total-alreadyPaid;
      const existingPayment=await db.prepare("SELECT id,amount_minor,status FROM invoice_payments WHERE board_id=? AND entity_type='supplier_invoice' AND entity_id=? AND bank_transaction_id IS NULL AND payment_reference=? AND status<>'reversed' LIMIT 1").bind(boardId,invoiceId,paymentReference).first<Record<string,unknown>>(); if(existingPayment){const existingAmount=Number(existingPayment.amount_minor||0); if(requestedAmount!==null && existingAmount!==requestedAmount)return json({error:'payment_reference_conflict',detail:'Betalingsreferansen er allerede brukt med et annet beløp.',existingPaymentId:String(existingPayment.id),existingAmountMinor:existingAmount},{status:409}); return json({ok:true,action,invoiceId,status:String(invoice.status),paymentSource:'manual',paymentId:String(existingPayment.id),amountMinor:existingAmount,paidMinor:alreadyPaid,remainingMinor:remaining,idempotent:true,externalPayment:'not_configured'});}
      if(!['approved','booked'].includes(String(invoice.status))) return json({error:'supplier_invoice_not_payable_or_found',detail:'Fakturaen må være attestert og anvist før betaling kan registreres.'},{status:409}); const paymentAmount=requestedAmount ?? remaining; if(paymentAmount<=0 || paymentAmount>remaining)return json({error:'payment_exceeds_remaining',remainingMinor:remaining},{status:409}); const nextPaid=alreadyPaid+paymentAmount,nextStatus=nextPaid===total?'paid':invoice.status,paymentId=newId('ipmt');
      await db.batch([db.prepare('INSERT INTO invoice_payments (id,board_id,entity_type,entity_id,amount_minor,payment_reference,status,recorded_by) VALUES (?,?,?,?,?,?,?,?)').bind(paymentId,boardId,'supplier_invoice',invoiceId,paymentAmount,paymentReference,'recorded',auth.userId||'service'),db.prepare("UPDATE supplier_invoices SET paid_minor=?,status=?,paid_at=CASE WHEN ?=? THEN datetime('now') ELSE paid_at END,payment_reference=? WHERE id=? AND board_id=?").bind(nextPaid,nextStatus,nextPaid,total,paymentReference,invoiceId,boardId)]);
      await recordAudit(db, { boardId, action: 'supplier_invoice_payment_recorded', entityType: 'supplier_invoice', entityId: invoiceId, userId: auth.userId || undefined, details: { status: nextStatus, paymentSource: 'manual', paymentId, amountMinor: paymentAmount, remainingMinor: total-nextPaid, externalPayment: 'not_configured' } }); return json({ ok: true, action, invoiceId, status: nextStatus, paymentSource: 'manual', paymentId, amountMinor: paymentAmount, paidMinor: nextPaid, remainingMinor: total-nextPaid, externalPayment: 'not_configured' });
    }
    const invoiceId = txt(v?.invoiceId, 100); const invoice = await db.prepare("SELECT attested_by,assigned_at FROM supplier_invoices WHERE id=? AND board_id=? AND status='matched' AND match_status='matched'").bind(invoiceId, boardId).first<{ attested_by: string | null; assigned_at: string | null }>(); if (!invoice || !invoice.attested_by || invoice.assigned_at) return json({ error: 'invoice_not_ready_for_assignment' }, { status: 409 }); if (invoice.attested_by === actor && auth.role !== 'owner') return json({ error: 'four_eyes_required', detail: 'Attestant og anviser må være ulike personer, med mindre eierrollen eksplisitt overstyrer.' }, { status: 409 });
    const result = await db.prepare("UPDATE supplier_invoices SET status='approved',assigned_by=?,assigned_at=datetime('now'),approved_by=?,approved_at=datetime('now') WHERE id=? AND board_id=? AND status='matched' AND attested_at IS NOT NULL AND assigned_at IS NULL").bind(actor, actor, invoiceId, boardId).run(); if (!result.meta?.changes) return json({ error: 'invoice_not_ready_for_assignment' }, { status: 409 }); await recordAudit(db, { boardId, action: 'supplier_invoice_assigned', entityType: 'supplier_invoice', entityId: invoiceId, userId: auth.userId || undefined, details: { attestedBy: invoice.attested_by, assignedBy: actor, ownerOverride: invoice.attested_by === actor && auth.role === 'owner', payment: 'not_configured' } }); return json({ ok: true, action, invoiceId, status: 'approved', approvalStage: 'assigned', fourEyes: invoice.attested_by !== actor, ownerOverride: invoice.attested_by === actor && auth.role === 'owner', payment: 'not_configured' });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};
