import { authorizeBoardRead, authorizeBoardWrite, body, json, recordAudit, requireDb, type Env } from './_lib';

const views = new Set(['summary', 'suppliers', 'orders', 'receipts', 'invoices', 'invoice-lines', 'ehf', 'ehf-xml']);
const actions = ['create_supplier', 'update_supplier', 'create_order', 'approve_order', 'create_receipt', 'create_invoice', 'match_invoice', 'attest_invoice', 'assign_invoice', 'record_invoice_payment', 'receive_ehf', 'validate_ehf', 'link_ehf_invoice'];
const txt = (v: unknown, max = 200) => String(v ?? '').trim().slice(0, max);
const num = (v: unknown) => Number.isFinite(Number(v)) && Number(v) >= 0 ? Math.round(Number(v)) : null;
const isoDate = (v: unknown) => {
  const value = String(v ?? '').trim();
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return null;
  const parsed = new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(parsed.valueOf()) && parsed.toISOString().slice(0, 10) === value ? value : null;
};
const newId = (p: string) => `${p}-${crypto.randomUUID()}`;
const validOrgNumber = (value: unknown) => {
  const digits = String(value ?? '').replace(/\s/g, '');
  if (!/^\d{9}$/.test(digits)) return false;
  const sum = [3, 2, 7, 6, 5, 4, 3, 2].reduce((total, weight, index) => total + Number(digits[index]) * weight, 0);
  const remainder = 11 - (sum % 11);
  return remainder !== 10 && (remainder === 11 ? 0 : remainder) === Number(digits.at(-1));
};

const xmlEscape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' }[char] || char));

function buildEhfInvoiceXml(document: Record<string, unknown>, lines: Record<string, unknown>[]) {
  const amount = (value: unknown) => (Number(value || 0) / 100).toFixed(2);
  const currency = xmlEscape(document.currency || 'NOK');
  const lineXml = lines.map((line) => `<cac:InvoiceLine><cbc:ID>${xmlEscape(line.line_number)}</cbc:ID><cbc:InvoicedQuantity unitCode="C62">${xmlEscape(line.quantity)}</cbc:InvoicedQuantity><cbc:LineExtensionAmount currencyID="${currency}">${amount(line.net_minor)}</cbc:LineExtensionAmount><cac:Item><cbc:Name>${xmlEscape(line.description)}</cbc:Name><cac:ClassifiedTaxCategory><cbc:ID>${Number(line.vat_rate || 0) ? 'S' : 'Z'}</cbc:ID><cbc:Percent>${xmlEscape(line.vat_rate || 0)}</cbc:Percent><cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme></cac:ClassifiedTaxCategory></cac:Item><cac:Price><cbc:PriceAmount currencyID="${currency}">${amount(line.unit_price_minor)}</cbc:PriceAmount></cac:Price></cac:InvoiceLine>`).join('');
  return `<?xml version="1.0" encoding="UTF-8"?><Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"><cbc:UBLVersionID>2.1</cbc:UBLVersionID><cbc:CustomizationID>urn:cen.eu:en16931:2017</cbc:CustomizationID><cbc:ProfileID>urn:fdc:peppol.eu:2017:poacc:billing:3.0</cbc:ProfileID><cbc:ID>${xmlEscape(document.invoice_number)}</cbc:ID><cbc:IssueDate>${xmlEscape(document.issue_date)}</cbc:IssueDate><cbc:DueDate>${xmlEscape(document.due_date)}</cbc:DueDate><cbc:DocumentCurrencyCode>${currency}</cbc:DocumentCurrencyCode><cac:AccountingSupplierParty><cac:Party><cac:PartyName><cbc:Name>${xmlEscape(document.supplier_name)}</cbc:Name></cac:PartyName></cac:Party></cac:AccountingSupplierParty><cac:AccountingCustomerParty><cac:Party><cac:PartyName><cbc:Name>Styr.ing-kunde</cbc:Name></cac:PartyName></cac:Party></cac:AccountingCustomerParty><cac:TaxTotal><cbc:TaxAmount currencyID="${currency}">${amount(document.vat_minor)}</cbc:TaxAmount></cac:TaxTotal><cac:LegalMonetaryTotal><cbc:LineExtensionAmount currencyID="${currency}">${amount(Number(document.amount_minor || 0) - Number(document.vat_minor || 0))}</cbc:LineExtensionAmount><cbc:TaxExclusiveAmount currencyID="${currency}">${amount(Number(document.amount_minor || 0) - Number(document.vat_minor || 0))}</cbc:TaxExclusiveAmount><cbc:TaxInclusiveAmount currencyID="${currency}">${amount(document.amount_minor)}</cbc:TaxInclusiveAmount><cbc:PayableAmount currencyID="${currency}">${amount(document.amount_minor)}</cbc:PayableAmount></cac:LegalMonetaryTotal>${lineXml}</Invoice>`;
}

export const onRequestGet: PagesFunction<Env> = async ({ env, request }) => {
  const u = new URL(request.url); const boardId = txt(u.searchParams.get('boardId')); const view = u.searchParams.get('view') || 'summary'; const invoiceId = txt(u.searchParams.get('invoiceId'));
  if (!boardId) return json({ error: 'boardId_required' }, { status: 400 }); if (!views.has(view)) return json({ error: 'unknown_view', allowed: [...views] }, { status: 400 });
  if (!(await authorizeBoardRead(request, env, boardId))) return json({ error: 'board_access_denied' }, { status: 403 });
  try {
    const db = requireDb(env); const q: Record<string, string> = { suppliers: 'SELECT s.*,a.code AS default_expense_account_code,a.name AS default_expense_account_name FROM supplier_parties s LEFT JOIN ledger_accounts a ON a.id=s.default_expense_account_id WHERE s.board_id=? ORDER BY s.active DESC,s.name', orders: 'SELECT o.*,s.name AS supplier_party_name FROM purchase_orders o LEFT JOIN supplier_parties s ON s.id=o.supplier_party_id WHERE o.board_id=? ORDER BY o.created_at DESC', receipts: 'SELECT r.*,o.order_number,o.supplier_name FROM goods_receipts r JOIN purchase_orders o ON o.id=r.purchase_order_id WHERE r.board_id=? ORDER BY r.received_date DESC', invoices: 'SELECT i.*,o.order_number,s.name AS supplier_party_name,(SELECT COUNT(*) FROM supplier_invoice_lines l WHERE l.supplier_invoice_id=i.id) AS line_count FROM supplier_invoices i LEFT JOIN purchase_orders o ON o.id=i.purchase_order_id LEFT JOIN supplier_parties s ON s.id=i.supplier_party_id WHERE i.board_id=? ORDER BY i.due_date', 'invoice-lines': 'SELECT * FROM supplier_invoice_lines WHERE board_id=? AND supplier_invoice_id=? ORDER BY line_number', ehf: 'SELECT e.*,i.status invoice_status FROM ehf_documents e LEFT JOIN supplier_invoices i ON i.id=e.supplier_invoice_id WHERE e.board_id=? ORDER BY e.created_at DESC' };
    if (view !== 'summary') {
      if ((view === 'invoice-lines' || view === 'ehf-xml') && !invoiceId) return json({ error: 'invoiceId_required' }, { status: 400 });
      if (view === 'ehf-xml') {
        const document = await db.prepare("SELECT * FROM ehf_documents WHERE id=? AND board_id=? AND status IN ('validated','linked')").bind(invoiceId, boardId).first<Record<string, unknown>>();
        if (!document) return json({ error: 'ehf_not_validated_or_found' }, { status: 409 });
        const lines = (await db.prepare('SELECT * FROM ehf_document_lines WHERE board_id=? AND ehf_document_id=? ORDER BY line_number').bind(boardId, invoiceId).all()).results as Record<string, unknown>[];
        const xml = buildEhfInvoiceXml(document, lines);
        return new Response(xml, { headers: { 'content-type': 'application/xml; charset=utf-8', 'content-disposition': `attachment; filename="${txt(document.invoice_number, 80).replace(/[^A-Za-z0-9._-]/g, '_')}.xml"`, 'cache-control': 'no-store' } });
      }
      return json({ boardId, view, data: (await db.prepare(q[view]).bind(...(view === 'invoice-lines' ? [boardId, invoiceId] : [boardId])).all()).results });
    }
    const [orders, receipts, invoices, exceptions, ehf] = await Promise.all([db.prepare("SELECT COUNT(*) count,COALESCE(SUM(total_minor),0) total_minor FROM purchase_orders WHERE board_id=? AND status NOT IN ('closed','cancelled')").bind(boardId).first(), db.prepare("SELECT COUNT(*) count FROM goods_receipts WHERE board_id=? AND status='confirmed'").bind(boardId).first(), db.prepare("SELECT COUNT(*) count,COALESCE(SUM(MAX(0,amount_minor-paid_minor)),0) amount_minor FROM supplier_invoices WHERE board_id=? AND status NOT IN ('paid','cancelled') AND amount_minor>paid_minor").bind(boardId).first(), db.prepare("SELECT COUNT(*) count FROM supplier_invoices WHERE board_id=? AND match_status='exception'").bind(boardId).first(), db.prepare("SELECT COUNT(*) count FROM ehf_documents WHERE board_id=? AND status IN ('received','validated')").bind(boardId).first()]);
    return json({ boardId, view, data: { orders, receipts, invoices, exceptions, ehf, transport: 'not_configured' } });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};

export const onRequestPost: PagesFunction<Env> = async ({ env, request }) => {
  try {
    const v = await body(request); const boardId = txt(v?.boardId); const action = txt(v?.action, 40); const db = requireDb(env);
    if (!boardId || !action) return json({ error: 'boardId_and_action_required' }, { status: 400 }); if (!actions.includes(action)) return json({ error: 'unknown_action', allowed: actions }, { status: 400 });
    const auth = await authorizeBoardWrite(request, env, boardId); if (!auth.allowed) return json({ error: 'write_not_authorized' }, { status: 401 }); const actor = auth.userId || 'api';
    if (action === 'create_supplier') {
      const name = txt(v?.name), rawOrg = txt(v?.orgNumber, 20).replace(/\s/g, ''), orgNumber = rawOrg || null;
      const address = txt(v?.addressLine1), postalCode = txt(v?.postalCode, 4), city = txt(v?.city, 100), countryCode = (txt(v?.countryCode, 2) || 'NO').toUpperCase(), email = txt(v?.email, 200) || null;
      const paymentTermsDays = Number(v?.paymentTermsDays ?? 14), defaultExpenseAccountId = txt(v?.defaultExpenseAccountId, 120) || null;
      if (!name || name.length > 200 || (orgNumber && !validOrgNumber(orgNumber)) || !/^[A-Z]{2}$/.test(countryCode) || (postalCode && !/^\d{4}$/.test(postalCode)) || (email && (!email.includes('@') || email.length > 200)) || !Number.isInteger(paymentTermsDays) || paymentTermsDays < 0 || paymentTermsDays > 365) return json({ error: 'supplier_fields_invalid', detail: 'Navn, organisasjonsnummer, postnummer, e-post eller betalingsfrist er ugyldig.' }, { status: 400 });
      if (orgNumber && await db.prepare('SELECT id FROM supplier_parties WHERE board_id=? AND org_number=? LIMIT 1').bind(boardId, orgNumber).first()) return json({ error: 'supplier_org_number_exists', detail: 'Leverandøren finnes allerede i leverandørregisteret.' }, { status: 409 });
      if (defaultExpenseAccountId && !(await db.prepare("SELECT id FROM ledger_accounts WHERE id=? AND board_id=? AND active=1").bind(defaultExpenseAccountId, boardId).first())) return json({ error: 'supplier_account_not_found' }, { status: 400 });
      const supplierId = newId('sup'); await db.prepare('INSERT INTO supplier_parties (id,board_id,name,org_number,address_line1,postal_code,city,country_code,email,payment_terms_days,default_expense_account_id,active) VALUES (?,?,?,?,?,?,?,?,?,?,?,1)').bind(supplierId, boardId, name, orgNumber, address || null, postalCode || null, city || null, countryCode, email, paymentTermsDays, defaultExpenseAccountId).run();
      await recordAudit(db, { boardId, action: 'supplier_party_created', entityType: 'supplier_party', entityId: supplierId, userId: auth.userId || undefined, details: { hasOrgNumber: Boolean(orgNumber), paymentTermsDays } }); return json({ ok: true, action, supplierId, status: 'active' }, { status: 201 });
    }
    if (action === 'update_supplier') {
      const supplierId = txt(v?.supplierId, 120), name = txt(v?.name), rawOrg = txt(v?.orgNumber, 20).replace(/\s/g, ''), orgNumber = rawOrg || null;
      const address = txt(v?.addressLine1), postalCode = txt(v?.postalCode, 4), city = txt(v?.city, 100), countryCode = (txt(v?.countryCode, 2) || 'NO').toUpperCase(), email = txt(v?.email, 200) || null, paymentTermsDays = Number(v?.paymentTermsDays ?? 14), defaultExpenseAccountId = txt(v?.defaultExpenseAccountId, 120) || null, active = v?.active === false || String(v?.active) === '0' ? 0 : 1;
      if (!supplierId || !name || (orgNumber && !validOrgNumber(orgNumber)) || !/^[A-Z]{2}$/.test(countryCode) || (postalCode && !/^\d{4}$/.test(postalCode)) || (email && (!email.includes('@') || email.length > 200)) || !Number.isInteger(paymentTermsDays) || paymentTermsDays < 0 || paymentTermsDays > 365) return json({ error: 'supplier_fields_invalid' }, { status: 400 });
      if (orgNumber && await db.prepare('SELECT id FROM supplier_parties WHERE board_id=? AND org_number=? AND id<>? LIMIT 1').bind(boardId, orgNumber, supplierId).first()) return json({ error: 'supplier_org_number_exists' }, { status: 409 });
      if (defaultExpenseAccountId && !(await db.prepare("SELECT id FROM ledger_accounts WHERE id=? AND board_id=? AND active=1").bind(defaultExpenseAccountId, boardId).first())) return json({ error: 'supplier_account_not_found' }, { status: 400 });
      const result = await db.prepare('UPDATE supplier_parties SET name=?,org_number=?,address_line1=?,postal_code=?,city=?,country_code=?,email=?,payment_terms_days=?,default_expense_account_id=?,active=?,updated_at=datetime(\'now\') WHERE id=? AND board_id=?').bind(name, orgNumber, address || null, postalCode || null, city || null, countryCode, email, paymentTermsDays, defaultExpenseAccountId, active, supplierId, boardId).run();
      if (!result.meta?.changes) return json({ error: 'supplier_not_found' }, { status: 404 }); await recordAudit(db, { boardId, action: 'supplier_party_updated', entityType: 'supplier_party', entityId: supplierId, userId: auth.userId || undefined, details: { active } }); return json({ ok: true, action, supplierId, status: active ? 'active' : 'inactive' });
    }
    if (action === 'create_order') {
      const orderNumber = txt(v?.orderNumber, 60), supplierPartyId = txt(v?.supplierPartyId, 120) || null, linkedSupplier = supplierPartyId ? await db.prepare('SELECT id,name FROM supplier_parties WHERE id=? AND board_id=? AND active=1').bind(supplierPartyId, boardId).first<{ id: string; name: string }>() : null;
      const supplierName = txt(v?.supplierName) || String(linkedSupplier?.name || ''), totalMinor = num(v?.totalMinor), currency = txt(v?.currency, 3).toUpperCase(); if (!orderNumber || !supplierName || totalMinor === null || !/^[A-Z]{3}$/.test(currency) || (supplierPartyId && !linkedSupplier)) return json({ error: 'order_fields_invalid' }, { status: 400 });
      const orderId = newId('po'); await db.prepare("INSERT INTO purchase_orders (id,board_id,order_number,supplier_name,supplier_party_id,status,total_minor,currency,requested_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,datetime('now'))").bind(orderId, boardId, orderNumber, supplierName, supplierPartyId, 'pending_approval', totalMinor, currency, actor).run(); await recordAudit(db, { boardId, action: 'purchase_order_created', entityType: 'purchase_order', entityId: orderId, userId: auth.userId || undefined, details: { status: 'pending_approval', supplierPartyId } }); return json({ ok: true, action, orderId, status: 'pending_approval', supplierPartyId }, { status: 201 });
    }
    if (action === 'approve_order') {
      const orderId = txt(v?.orderId, 100), result = await db.prepare("UPDATE purchase_orders SET status='approved',approved_by=?,approved_at=datetime('now') WHERE id=? AND board_id=? AND status='pending_approval'").bind(txt(v?.approvedBy, 120) || actor, orderId, boardId).run(); if (!result.meta?.changes) return json({ error: 'order_not_pending_or_found' }, { status: 409 }); await recordAudit(db, { boardId, action: 'purchase_order_approved', entityType: 'purchase_order', entityId: orderId, userId: auth.userId || undefined, details: { externalOrdering: 'not_configured' } }); return json({ ok: true, action, orderId, status: 'approved', externalOrdering: 'not_configured' });
    }
    if (action === 'create_receipt') {
      const purchaseOrderId = txt(v?.purchaseOrderId, 100), receivedDate = isoDate(v?.receivedDate), receiptStatus = ['draft', 'confirmed', 'disputed'].includes(txt(v?.status, 20)) ? txt(v?.status, 20) : 'draft'; if (!purchaseOrderId || !receivedDate) return json({ error: 'receipt_fields_invalid' }, { status: 400 }); if (!(await db.prepare('SELECT id FROM purchase_orders WHERE id=? AND board_id=?').bind(purchaseOrderId, boardId).first())) return json({ error: 'purchase_order_not_found' }, { status: 404 });
      const receiptId = newId('gr'); await db.prepare("INSERT INTO goods_receipts (id,board_id,purchase_order_id,received_date,received_by,status,notes,created_at) VALUES (?,?,?,?,?,?,?,datetime('now'))").bind(receiptId, boardId, purchaseOrderId, receivedDate, actor, receiptStatus, txt(v?.notes, 500)).run(); await recordAudit(db, { boardId, action: 'goods_receipt_created', entityType: 'goods_receipt', entityId: receiptId, userId: auth.userId || undefined, details: { status: receiptStatus } }); return json({ ok: true, action, receiptId, status: receiptStatus }, { status: 201 });
    }
    if (action === 'create_invoice') {
      const invoiceNumber = txt(v?.invoiceNumber, 80), supplierPartyId = txt(v?.supplierPartyId, 120) || null, linkedSupplier = supplierPartyId ? await db.prepare('SELECT id,name FROM supplier_parties WHERE id=? AND board_id=? AND active=1').bind(supplierPartyId, boardId).first<{ id: string; name: string }>() : null, supplierName = txt(v?.supplierName) || String(linkedSupplier?.name || ''), currency = txt(v?.currency, 3).toUpperCase(), dueDate = isoDate(v?.dueDate), purchaseOrderId = txt(v?.purchaseOrderId, 100) || null;
      const rawLines = Array.isArray(v?.lines) ? v.lines : [];
      const lines = rawLines.length ? rawLines : [{ description: txt(v?.description, 200) || 'Leverandørkjøp', quantity: 1, unitPriceMinor: num(v?.amountMinor), vatRate: 0, accountId: txt(v?.accountId, 120) || null }];
      if (!invoiceNumber || !supplierName || !dueDate || !/^[A-Z]{3}$/.test(currency) || lines.length > 100 || (supplierPartyId && !linkedSupplier)) return json({ error: 'invoice_fields_invalid' }, { status: 400 });
      const normalized: Array<Record<string, unknown>> = [];
      for (let index = 0; index < lines.length; index += 1) {
        const line = lines[index] || {}; const description = txt(line.description, 200); const quantity = Number(line.quantity); const unitPriceMinor = num(line.unitPriceMinor); const vatRate = Number(line.vatRate);
        if (!description || !Number.isFinite(quantity) || quantity <= 0 || quantity > 100000 || unitPriceMinor === null || unitPriceMinor < 0 || ![0,12,15,25].includes(vatRate)) return json({ error: 'invoice_line_invalid', line: index + 1 }, { status: 400 });
        const netMinor = Math.round(quantity * unitPriceMinor); const vatMinor = Math.round(netMinor * vatRate / 100); normalized.push({ lineNumber: index + 1, description, quantity, unitPriceMinor, vatRate, vatCode: vatRate === 12 ? '1_12' : vatRate === 15 ? '1_15' : vatRate === 25 ? '1' : null, netMinor, vatMinor, totalMinor: netMinor + vatMinor, accountId: txt(line.accountId, 120) || null });
      }
      const amountMinor = normalized.reduce((sum, line) => sum + Number(line.totalMinor), 0); const vatMinor = normalized.reduce((sum, line) => sum + Number(line.vatMinor), 0);
      if (amountMinor <= 0) return json({ error: 'invoice_amount_invalid' }, { status: 400 }); if (purchaseOrderId && !(await db.prepare('SELECT id FROM purchase_orders WHERE id=? AND board_id=?').bind(purchaseOrderId, boardId).first())) return json({ error: 'purchase_order_not_found' }, { status: 404 });
      const invoiceId = newId('si'); const statements = [db.prepare("INSERT INTO supplier_invoices (id,board_id,purchase_order_id,invoice_number,supplier_name,supplier_party_id,amount_minor,vat_minor,currency,due_date,status,match_status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,datetime('now'))").bind(invoiceId, boardId, purchaseOrderId, invoiceNumber, supplierName, supplierPartyId, amountMinor, vatMinor, currency, dueDate, 'received', 'unmatched')];
      for (const line of normalized) statements.push(db.prepare('INSERT INTO supplier_invoice_lines (id,board_id,supplier_invoice_id,line_number,description,quantity,unit_price_minor,vat_rate,vat_code,net_minor,vat_minor,total_minor,account_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(newId('sil'), boardId, invoiceId, line.lineNumber, line.description, line.quantity, line.unitPriceMinor, line.vatRate, line.vatCode, line.netMinor, line.vatMinor, line.totalMinor, line.accountId));
      await db.batch(statements); await recordAudit(db, { boardId, action: 'supplier_invoice_created', entityType: 'supplier_invoice', entityId: invoiceId, userId: auth.userId || undefined, details: { purchaseOrderId, supplierPartyId, lineCount: normalized.length, amountMinor, vatMinor } }); return json({ ok: true, action, invoiceId, supplierPartyId, status: 'received', matchStatus: 'unmatched', amountMinor, vatMinor, lineCount: normalized.length }, { status: 201 });
    }
    if (action === 'receive_ehf') {
      const documentRef = txt(v?.documentRef, 120), supplierName = txt(v?.supplierName), invoiceNumber = txt(v?.invoiceNumber, 80), issueDate = isoDate(v?.issueDate), dueDate = isoDate(v?.dueDate), currency = txt(v?.currency, 3).toUpperCase();
      const rawLines = Array.isArray(v?.lines) ? v.lines : []; const lines = rawLines.length ? rawLines : [{ description: 'EHF-kjøp', quantity: 1, unitPriceMinor: num(v?.amountMinor), vatRate: 0 }]; const normalized: Array<Record<string, unknown>> = [];
      for (let index = 0; index < lines.length; index += 1) { const line = lines[index] || {}; const description = txt(line.description, 200), quantity = Number(line.quantity), unitPriceMinor = num(line.unitPriceMinor), vatRate = Number(line.vatRate); if (!description || !Number.isFinite(quantity) || quantity <= 0 || unitPriceMinor === null || ![0,12,15,25].includes(vatRate)) return json({ error: 'ehf_line_invalid', line: index + 1 }, { status: 400 }); const netMinor = Math.round(quantity * unitPriceMinor); const vatMinor = Math.round(netMinor * vatRate / 100); normalized.push({ lineNumber: index + 1, description, quantity, unitPriceMinor, vatRate, vatCode: vatRate === 12 ? '1_12' : vatRate === 15 ? '1_15' : vatRate === 25 ? '1' : null, netMinor, vatMinor, totalMinor: netMinor + vatMinor, accountId: txt(line.accountId, 120) || null }); }
      const amountMinor = normalized.reduce((sum, line) => sum + Number(line.totalMinor), 0), vatMinor = normalized.reduce((sum, line) => sum + Number(line.vatMinor), 0);
      if (!documentRef || !supplierName || !invoiceNumber || !issueDate || !dueDate || dueDate < issueDate || amountMinor <= 0 || !/^[A-Z]{3}$/.test(currency) || normalized.length > 100) return json({ error: 'ehf_fields_invalid', required: ['documentRef','supplierName','invoiceNumber','issueDate','dueDate_on_or_after_issue_date','lines','currency'] }, { status: 400 });
      const ehfId = newId('ehf'); const statements = [db.prepare("INSERT INTO ehf_documents (id,board_id,document_ref,standard,profile,supplier_name,supplier_org_number,invoice_number,issue_date,due_date,amount_minor,vat_minor,currency,source,status,external_status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'received','not_configured')").bind(ehfId, boardId, documentRef, txt(v?.standard, 40) || 'EHF 3.0', txt(v?.profile, 160) || null, supplierName, txt(v?.supplierOrgNumber, 30) || null, invoiceNumber, issueDate, dueDate, amountMinor, vatMinor, currency, ['manual','upload','peppol'].includes(txt(v?.source, 20)) ? txt(v?.source, 20) : 'manual')];
      for (const line of normalized) statements.push(db.prepare('INSERT INTO ehf_document_lines (id,board_id,ehf_document_id,line_number,description,quantity,unit_price_minor,vat_rate,vat_code,net_minor,vat_minor,total_minor,account_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(newId('ehfl'), boardId, ehfId, line.lineNumber, line.description, line.quantity, line.unitPriceMinor, line.vatRate, line.vatCode, line.netMinor, line.vatMinor, line.totalMinor, line.accountId)); await db.batch(statements); await recordAudit(db, { boardId, action: 'ehf_document_received', entityType: 'ehf_document', entityId: ehfId, userId: auth.userId || undefined, details: { source: txt(v?.source, 20) || 'manual', transport: 'not_configured', lineCount: normalized.length, amountMinor, vatMinor } }); return json({ ok: true, action, ehfId, status: 'received', amountMinor, vatMinor, lineCount: normalized.length, transport: 'not_configured' }, { status: 201 });
    }
    if (action === 'validate_ehf') {
      const ehfId = txt(v?.ehfId, 100); const document = await db.prepare("SELECT * FROM ehf_documents WHERE id=? AND board_id=? AND status IN ('received','rejected')").bind(ehfId, boardId).first<Record<string, unknown>>(); if (!document) return json({ error: 'ehf_not_received_or_found' }, { status: 409 });
      const lines = (await db.prepare('SELECT line_number,description,quantity,unit_price_minor,vat_rate,net_minor,vat_minor,total_minor FROM ehf_document_lines WHERE board_id=? AND ehf_document_id=? ORDER BY line_number').bind(boardId, ehfId).all()).results as Record<string, unknown>[];
      const errors: string[] = []; if (!txt(document.supplier_name)) errors.push('supplier_name_missing'); if (!txt(document.invoice_number)) errors.push('invoice_number_missing'); if (!isoDate(document.issue_date)) errors.push('issue_date_invalid'); if (!isoDate(document.due_date)) errors.push('due_date_invalid'); if (Number(document.amount_minor || 0) <= 0) errors.push('amount_invalid'); if (!/^[A-Z]{3}$/.test(txt(document.currency, 3))) errors.push('currency_invalid'); if (!lines.length) errors.push('lines_missing');
      const lineAmount = lines.reduce((sum, line) => sum + Number(line.total_minor || 0), 0), lineVat = lines.reduce((sum, line) => sum + Number(line.vat_minor || 0), 0); if (lines.length && lineAmount !== Number(document.amount_minor || 0)) errors.push('line_total_mismatch'); if (lines.length && lineVat !== Number(document.vat_minor || 0)) errors.push('vat_total_mismatch');
      const status = errors.length ? 'rejected' : 'validated'; await db.prepare('UPDATE ehf_documents SET status=?,validation_errors=?,validated_at=datetime(\'now\') WHERE id=? AND board_id=?').bind(status, errors.length ? JSON.stringify(errors) : null, ehfId, boardId).run(); await recordAudit(db, { boardId, action: 'ehf_document_validated', entityType: 'ehf_document', entityId: ehfId, userId: auth.userId || undefined, details: { status, errors, lineCount: lines.length, transport: 'not_configured' } }); return json({ ok: !errors.length, action, ehfId, status, errors, lineCount: lines.length, requiresHumanReview: true });
    }
    if (action === 'link_ehf_invoice') {
      const ehfId = txt(v?.ehfId, 100); const document = await db.prepare("SELECT * FROM ehf_documents WHERE id=? AND board_id=? AND status='validated' AND supplier_invoice_id IS NULL").bind(ehfId, boardId).first<Record<string, unknown>>(); if (!document) return json({ error: 'ehf_not_validated_or_already_linked' }, { status: 409 });
      const invoiceId = newId('si'); const ehfLines = (await db.prepare('SELECT * FROM ehf_document_lines WHERE board_id=? AND ehf_document_id=? ORDER BY line_number').bind(boardId, ehfId).all()).results as Record<string, unknown>[]; const statements = [db.prepare("INSERT INTO supplier_invoices (id,board_id,invoice_number,supplier_name,amount_minor,vat_minor,currency,due_date,status,match_status,external_reference,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,datetime('now'))").bind(invoiceId, boardId, txt(document.invoice_number, 80), txt(document.supplier_name), Number(document.amount_minor), Number(document.vat_minor || 0), txt(document.currency, 3), txt(document.due_date, 20), 'received', 'unmatched', `EHF:${txt(document.document_ref, 120)}`)]; for (const line of ehfLines) statements.push(db.prepare('INSERT INTO supplier_invoice_lines (id,board_id,supplier_invoice_id,line_number,description,quantity,unit_price_minor,vat_rate,vat_code,net_minor,vat_minor,total_minor,account_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(newId('sil'), boardId, invoiceId, line.line_number, line.description, line.quantity, line.unit_price_minor, line.vat_rate, line.vat_code, line.net_minor, line.vat_minor, line.total_minor, line.account_id)); await db.batch(statements); await db.prepare("UPDATE ehf_documents SET status='linked',supplier_invoice_id=? WHERE id=? AND board_id=?").bind(invoiceId, ehfId, boardId).run(); await recordAudit(db, { boardId, action: 'ehf_document_linked_to_invoice', entityType: 'ehf_document', entityId: ehfId, userId: auth.userId || undefined, details: { supplierInvoiceId: invoiceId, lineCount: ehfLines.length, nextStep: 'three_way_match' } });
      const xml = buildEhfInvoiceXml(document as Record<string, unknown>, ehfLines);
      return json({ ok: true, action, ehfId, supplierInvoiceId: invoiceId, status: 'linked', lineCount: ehfLines.length, nextStep: 'three_way_match', documentFormat: 'Peppol BIS Billing 3.0 / UBL 2.1', xml, transport: 'not_configured' }, { status: 201 });
    }
    if (action === 'match_invoice') {
      const invoiceId = txt(v?.invoiceId, 100); const invoice = await db.prepare("SELECT i.id,i.purchase_order_id,o.id order_id FROM supplier_invoices i LEFT JOIN purchase_orders o ON o.id=i.purchase_order_id WHERE i.id=? AND i.board_id=? AND i.status='received'").bind(invoiceId, boardId).first() as { id?: string; purchase_order_id?: string; order_id?: string } | null; if (!invoice) return json({ error: 'invoice_not_received_or_found' }, { status: 409 });
      if (!invoice.purchase_order_id || !invoice.order_id || !(await db.prepare("SELECT id FROM goods_receipts WHERE board_id=? AND purchase_order_id=? AND status='confirmed'").bind(boardId, invoice.purchase_order_id).first())) { await db.prepare("UPDATE supplier_invoices SET match_status='exception',status='exception' WHERE id=? AND board_id=?").bind(invoiceId, boardId).run(); return json({ error: 'three_way_match_required', invoiceId, status: 'exception' }, { status: 409 }); }
      await db.prepare("UPDATE supplier_invoices SET match_status='matched',status='matched' WHERE id=? AND board_id=? AND status='received'").bind(invoiceId, boardId).run(); await recordAudit(db, { boardId, action: 'supplier_invoice_matched', entityType: 'supplier_invoice', entityId: invoiceId, userId: auth.userId || undefined, details: { requiresHumanApproval: true, threeWayMatch: true } }); return json({ ok: true, action, invoiceId, status: 'matched', requiresHumanApproval: true });
    }
    if (action === 'attest_invoice') {
      const invoiceId = txt(v?.invoiceId, 100); const result = await db.prepare("UPDATE supplier_invoices SET attested_by=?,attested_at=datetime('now') WHERE id=? AND board_id=? AND status='matched' AND match_status='matched' AND attested_at IS NULL").bind(actor, invoiceId, boardId).run(); if (!result.meta?.changes) return json({ error: 'invoice_not_ready_for_attestation' }, { status: 409 }); await recordAudit(db, { boardId, action: 'supplier_invoice_attested', entityType: 'supplier_invoice', entityId: invoiceId, userId: auth.userId || undefined, details: { nextStep: 'anvisning', externalPayment: 'not_configured' } }); return json({ ok: true, action, invoiceId, status: 'matched', approvalStage: 'attested', nextStep: 'assign_invoice', payment: 'not_configured' });
    }
    if (action === 'record_invoice_payment') {
      const invoiceId = txt(v?.invoiceId, 100), paymentReference = txt(v?.paymentReference, 120); const requestedAmount = v?.amountMinor === undefined || v?.amountMinor === '' ? null : Number(v?.amountMinor); if (!paymentReference) return json({ error: 'payment_reference_required' }, { status: 400 }); if (requestedAmount !== null && (!Number.isSafeInteger(requestedAmount) || requestedAmount <= 0)) return json({ error: 'payment_amount_invalid' }, { status: 400 });
      const invoice=await db.prepare("SELECT amount_minor,paid_minor,status FROM supplier_invoices WHERE id=? AND board_id=?").bind(invoiceId,boardId).first<Record<string,unknown>>(); if(!invoice)return json({error:'supplier_invoice_not_payable_or_found',detail:'Fakturaen må være attestert og anvist før betaling kan registreres.'},{status:409});
      const total=Number(invoice.amount_minor||0),alreadyPaid=Number(invoice.paid_minor||0),remaining=total-alreadyPaid;
      const existingPayment=await db.prepare("SELECT id,amount_minor,status FROM invoice_payments WHERE board_id=? AND entity_type='supplier_invoice' AND entity_id=? AND bank_transaction_id IS NULL AND payment_reference=? AND status<>'reversed' LIMIT 1").bind(boardId,invoiceId,paymentReference).first<Record<string,unknown>>(); if(existingPayment){const existingAmount=Number(existingPayment.amount_minor||0); if(requestedAmount!==null && existingAmount!==requestedAmount)return json({error:'payment_reference_conflict',detail:'Betalingsreferansen er allerede brukt med et annet beløp.',existingPaymentId:String(existingPayment.id),existingAmountMinor:existingAmount},{status:409}); return json({ok:true,action,invoiceId,status:String(invoice.status),paymentSource:'manual',paymentId:String(existingPayment.id),amountMinor:existingAmount,paidMinor:alreadyPaid,remainingMinor:remaining,idempotent:true,externalPayment:'not_configured'});}
      if(!['approved','booked'].includes(String(invoice.status))) return json({error:'supplier_invoice_not_payable_or_found',detail:'Fakturaen må være attestert og anvist før betaling kan registreres.'},{status:409}); const paymentAmount=requestedAmount ?? remaining; if(paymentAmount<=0 || paymentAmount>remaining)return json({error:'payment_exceeds_remaining',remainingMinor:remaining},{status:409}); const nextPaid=alreadyPaid+paymentAmount,nextStatus=nextPaid===total?'paid':invoice.status,paymentId=newId('ipmt');
      try { await db.batch([db.prepare('INSERT INTO invoice_payments (id,board_id,entity_type,entity_id,amount_minor,payment_reference,status,recorded_by) VALUES (?,?,?,?,?,?,?,?)').bind(paymentId,boardId,'supplier_invoice',invoiceId,paymentAmount,paymentReference,'recorded',auth.userId||'service'),db.prepare("UPDATE supplier_invoices SET paid_minor=?,status=?,paid_at=CASE WHEN ?=? THEN datetime('now') ELSE paid_at END,payment_reference=? WHERE id=? AND board_id=?").bind(nextPaid,nextStatus,nextPaid,total,paymentReference,invoiceId,boardId)]); } catch(error) {
        if (!(error instanceof Error) || !error.message.toLowerCase().includes('unique')) throw error;
        const raced=await db.prepare("SELECT id,amount_minor,status FROM invoice_payments WHERE board_id=? AND entity_type='supplier_invoice' AND entity_id=? AND bank_transaction_id IS NULL AND payment_reference=? AND status<>'reversed' LIMIT 1").bind(boardId,invoiceId,paymentReference).first<Record<string,unknown>>();
        if(!raced||Number(raced.amount_minor||0)!==paymentAmount)return json({error:'payment_reference_conflict',detail:'En annen betaling brukte referansen samtidig med et annet beløp.'},{status:409});
        return json({ok:true,action,invoiceId,status:String(invoice.status),paymentSource:'manual',paymentId:String(raced.id),amountMinor:paymentAmount,paidMinor:alreadyPaid,remainingMinor:remaining,idempotent:true,externalPayment:'not_configured'});
      }
      await recordAudit(db, { boardId, action: 'supplier_invoice_payment_recorded', entityType: 'supplier_invoice', entityId: invoiceId, userId: auth.userId || undefined, details: { status: nextStatus, paymentSource: 'manual', paymentId, amountMinor: paymentAmount, remainingMinor: total-nextPaid, externalPayment: 'not_configured' } }); return json({ ok: true, action, invoiceId, status: nextStatus, paymentSource: 'manual', paymentId, amountMinor: paymentAmount, paidMinor: nextPaid, remainingMinor: total-nextPaid, externalPayment: 'not_configured' });
    }
    const invoiceId = txt(v?.invoiceId, 100); const invoice = await db.prepare("SELECT attested_by,assigned_at FROM supplier_invoices WHERE id=? AND board_id=? AND status='matched' AND match_status='matched'").bind(invoiceId, boardId).first<{ attested_by: string | null; assigned_at: string | null }>(); if (!invoice || !invoice.attested_by || invoice.assigned_at) return json({ error: 'invoice_not_ready_for_assignment' }, { status: 409 }); if (invoice.attested_by === actor && auth.role !== 'owner') return json({ error: 'four_eyes_required', detail: 'Attestant og anviser må være ulike personer, med mindre eierrollen eksplisitt overstyrer.' }, { status: 409 });
    const result = await db.prepare("UPDATE supplier_invoices SET status='approved',assigned_by=?,assigned_at=datetime('now'),approved_by=?,approved_at=datetime('now') WHERE id=? AND board_id=? AND status='matched' AND attested_at IS NOT NULL AND assigned_at IS NULL").bind(actor, actor, invoiceId, boardId).run(); if (!result.meta?.changes) return json({ error: 'invoice_not_ready_for_assignment' }, { status: 409 }); await recordAudit(db, { boardId, action: 'supplier_invoice_assigned', entityType: 'supplier_invoice', entityId: invoiceId, userId: auth.userId || undefined, details: { attestedBy: invoice.attested_by, assignedBy: actor, ownerOverride: invoice.attested_by === actor && auth.role === 'owner', payment: 'not_configured' } }); return json({ ok: true, action, invoiceId, status: 'approved', approvalStage: 'assigned', fourEyes: invoice.attested_by !== actor, ownerOverride: invoice.attested_by === actor && auth.role === 'owner', payment: 'not_configured' });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};
