import { authorizeBoardRead, authorizeBoardWrite, body, json, recordAudit, requireDb, type Env } from './_lib';

const views = new Set(['summary', 'orders', 'receipts', 'invoices']);
const actions = ['create_order', 'approve_order', 'create_receipt', 'create_invoice', 'match_invoice', 'approve_invoice'];
const txt = (v: unknown, max = 200) => String(v ?? '').trim().slice(0, max);
const num = (v: unknown) => Number.isFinite(Number(v)) && Number(v) >= 0 ? Math.round(Number(v)) : null;
const isoDate = (v: unknown) => /^\d{4}-\d{2}-\d{2}$/.test(String(v ?? '')) ? String(v) : null;
const newId = (p: string) => `${p}-${crypto.randomUUID()}`;

export const onRequestGet: PagesFunction<Env> = async ({ env, request }) => {
  const u = new URL(request.url); const boardId = txt(u.searchParams.get('boardId')); const view = u.searchParams.get('view') || 'summary';
  if (!boardId) return json({ error: 'boardId_required' }, { status: 400 }); if (!views.has(view)) return json({ error: 'unknown_view', allowed: [...views] }, { status: 400 });
  if (!(await authorizeBoardRead(request, env, boardId))) return json({ error: 'board_access_denied' }, { status: 403 });
  try {
    const db = requireDb(env); const q: Record<string, string> = { orders: 'SELECT * FROM purchase_orders WHERE board_id=? ORDER BY created_at DESC', receipts: 'SELECT r.*,o.order_number,o.supplier_name FROM goods_receipts r JOIN purchase_orders o ON o.id=r.purchase_order_id WHERE r.board_id=? ORDER BY r.received_date DESC', invoices: 'SELECT i.*,o.order_number FROM supplier_invoices i LEFT JOIN purchase_orders o ON o.id=i.purchase_order_id WHERE i.board_id=? ORDER BY i.due_date' };
    if (view !== 'summary') return json({ boardId, view, data: (await db.prepare(q[view]).bind(boardId).all()).results });
    const [orders, receipts, invoices, exceptions] = await Promise.all([db.prepare("SELECT COUNT(*) count,COALESCE(SUM(total_minor),0) total_minor FROM purchase_orders WHERE board_id=? AND status NOT IN ('closed','cancelled')").bind(boardId).first(), db.prepare("SELECT COUNT(*) count FROM goods_receipts WHERE board_id=? AND status='confirmed'").bind(boardId).first(), db.prepare("SELECT COUNT(*) count,COALESCE(SUM(amount_minor),0) amount_minor FROM supplier_invoices WHERE board_id=? AND status NOT IN ('paid','booked')").bind(boardId).first(), db.prepare("SELECT COUNT(*) count FROM supplier_invoices WHERE board_id=? AND match_status='exception'").bind(boardId).first()]);
    return json({ boardId, view, data: { orders, receipts, invoices, exceptions } });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};

export const onRequestPost: PagesFunction<Env> = async ({ env, request }) => {
  try {
    const v = await body(request); const boardId = txt(v?.boardId); const action = txt(v?.action, 40); const db = requireDb(env);
    if (!boardId || !action) return json({ error: 'boardId_and_action_required' }, { status: 400 }); if (!actions.includes(action)) return json({ error: 'unknown_action', allowed: actions }, { status: 400 });
    const auth = await authorizeBoardWrite(request, env, boardId); if (!auth.allowed) return json({ error: 'write_not_authorized' }, { status: 401 }); const actor = auth.userId || 'api';
    if (action === 'create_order') {
      const orderNumber = txt(v?.orderNumber, 60), supplierName = txt(v?.supplierName), totalMinor = num(v?.totalMinor), currency = txt(v?.currency, 3).toUpperCase(); if (!orderNumber || !supplierName || totalMinor === null || !/^[A-Z]{3}$/.test(currency)) return json({ error: 'order_fields_invalid' }, { status: 400 });
      const orderId = newId('po'); await db.prepare("INSERT INTO purchase_orders (id,board_id,order_number,supplier_name,status,total_minor,currency,requested_by,created_at) VALUES (?,?,?,?,?,?,?,?,datetime('now'))").bind(orderId, boardId, orderNumber, supplierName, 'pending_approval', totalMinor, currency, actor).run(); await recordAudit(db, { boardId, action: 'purchase_order_created', entityType: 'purchase_order', entityId: orderId, userId: auth.userId || undefined, details: { status: 'pending_approval' } }); return json({ ok: true, action, orderId, status: 'pending_approval' }, { status: 201 });
    }
    if (action === 'approve_order') {
      const orderId = txt(v?.orderId, 100), result = await db.prepare("UPDATE purchase_orders SET status='approved',approved_by=?,approved_at=datetime('now') WHERE id=? AND board_id=? AND status='pending_approval'").bind(txt(v?.approvedBy, 120) || actor, orderId, boardId).run(); if (!result.meta?.changes) return json({ error: 'order_not_pending_or_found' }, { status: 409 }); await recordAudit(db, { boardId, action: 'purchase_order_approved', entityType: 'purchase_order', entityId: orderId, userId: auth.userId || undefined, details: { externalOrdering: 'not_configured' } }); return json({ ok: true, action, orderId, status: 'approved', externalOrdering: 'not_configured' });
    }
    if (action === 'create_receipt') {
      const purchaseOrderId = txt(v?.purchaseOrderId, 100), receivedDate = isoDate(v?.receivedDate), receiptStatus = ['draft', 'confirmed', 'disputed'].includes(txt(v?.status, 20)) ? txt(v?.status, 20) : 'draft'; if (!purchaseOrderId || !receivedDate) return json({ error: 'receipt_fields_invalid' }, { status: 400 }); if (!(await db.prepare('SELECT id FROM purchase_orders WHERE id=? AND board_id=?').bind(purchaseOrderId, boardId).first())) return json({ error: 'purchase_order_not_found' }, { status: 404 });
      const receiptId = newId('gr'); await db.prepare("INSERT INTO goods_receipts (id,board_id,purchase_order_id,received_date,received_by,status,notes,created_at) VALUES (?,?,?,?,?,?,?,datetime('now'))").bind(receiptId, boardId, purchaseOrderId, receivedDate, actor, receiptStatus, txt(v?.notes, 500)).run(); await recordAudit(db, { boardId, action: 'goods_receipt_created', entityType: 'goods_receipt', entityId: receiptId, userId: auth.userId || undefined, details: { status: receiptStatus } }); return json({ ok: true, action, receiptId, status: receiptStatus }, { status: 201 });
    }
    if (action === 'create_invoice') {
      const invoiceNumber = txt(v?.invoiceNumber, 80), supplierName = txt(v?.supplierName), amountMinor = num(v?.amountMinor), currency = txt(v?.currency, 3).toUpperCase(), dueDate = isoDate(v?.dueDate), purchaseOrderId = txt(v?.purchaseOrderId, 100) || null; if (!invoiceNumber || !supplierName || amountMinor === null || !dueDate || !/^[A-Z]{3}$/.test(currency)) return json({ error: 'invoice_fields_invalid' }, { status: 400 }); if (purchaseOrderId && !(await db.prepare('SELECT id FROM purchase_orders WHERE id=? AND board_id=?').bind(purchaseOrderId, boardId).first())) return json({ error: 'purchase_order_not_found' }, { status: 404 });
      const invoiceId = newId('si'); await db.prepare("INSERT INTO supplier_invoices (id,board_id,purchase_order_id,invoice_number,supplier_name,amount_minor,currency,due_date,status,match_status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,datetime('now'))").bind(invoiceId, boardId, purchaseOrderId, invoiceNumber, supplierName, amountMinor, currency, dueDate, 'received', 'unmatched').run(); await recordAudit(db, { boardId, action: 'supplier_invoice_created', entityType: 'supplier_invoice', entityId: invoiceId, userId: auth.userId || undefined, details: { purchaseOrderId } }); return json({ ok: true, action, invoiceId, status: 'received', matchStatus: 'unmatched' }, { status: 201 });
    }
    if (action === 'match_invoice') {
      const invoiceId = txt(v?.invoiceId, 100); const invoice = await db.prepare("SELECT i.id,i.purchase_order_id,o.id order_id FROM supplier_invoices i LEFT JOIN purchase_orders o ON o.id=i.purchase_order_id WHERE i.id=? AND i.board_id=? AND i.status='received'").bind(invoiceId, boardId).first() as { id?: string; purchase_order_id?: string; order_id?: string } | null; if (!invoice) return json({ error: 'invoice_not_received_or_found' }, { status: 409 });
      if (!invoice.purchase_order_id || !invoice.order_id || !(await db.prepare("SELECT id FROM goods_receipts WHERE board_id=? AND purchase_order_id=? AND status='confirmed'").bind(boardId, invoice.purchase_order_id).first())) { await db.prepare("UPDATE supplier_invoices SET match_status='exception',status='exception' WHERE id=? AND board_id=?").bind(invoiceId, boardId).run(); return json({ error: 'three_way_match_required', invoiceId, status: 'exception' }, { status: 409 }); }
      await db.prepare("UPDATE supplier_invoices SET match_status='matched',status='matched' WHERE id=? AND board_id=? AND status='received'").bind(invoiceId, boardId).run(); await recordAudit(db, { boardId, action: 'supplier_invoice_matched', entityType: 'supplier_invoice', entityId: invoiceId, userId: auth.userId || undefined, details: { requiresHumanApproval: true, threeWayMatch: true } }); return json({ ok: true, action, invoiceId, status: 'matched', requiresHumanApproval: true });
    }
    const invoiceId = txt(v?.invoiceId, 100), result = await db.prepare("UPDATE supplier_invoices SET status='approved',approved_by=?,approved_at=datetime('now') WHERE id=? AND board_id=? AND status='matched' AND match_status='matched'").bind(actor, invoiceId, boardId).run(); if (!result.meta?.changes) return json({ error: 'invoice_not_matched_or_found' }, { status: 409 }); await recordAudit(db, { boardId, action: 'supplier_invoice_approved', entityType: 'supplier_invoice', entityId: invoiceId, userId: auth.userId || undefined, details: { payment: 'not_configured' } }); return json({ ok: true, action, invoiceId, status: 'approved', payment: 'not_configured' });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};
