import { authorizeBoardRead, authorizeBoardWrite, body, id, json, recordAudit, requireDb, sha256, type Env } from './_lib';

const views = new Set(['summary', 'items', 'transparency', 'transparency_reports']);
const scopes = new Set(['scope_1', 'scope_2', 'scope_3']);
const riskLevels = new Set(['low', 'medium', 'high', 'critical']);
const validYear = (v: unknown) => /^\d{4}$/.test(String(v || '').trim());

export const onRequestGet: PagesFunction<Env> = async ({ env, request }) => {
  const u = new URL(request.url); const boardId = (u.searchParams.get('boardId') || '').trim(); const view = u.searchParams.get('view') || 'summary';
  if (!boardId) return json({ error: 'boardId_required' }, { status: 400 }); if (!views.has(view)) return json({ error: 'unknown_view', allowed: [...views] }, { status: 400 }); if (!(await authorizeBoardRead(request, env, boardId))) return json({ error: 'board_access_denied' }, { status: 403 });
  try { const db = requireDb(env);
    if (view === 'items') return json({ boardId, view, data: (await db.prepare("SELECT * FROM sustainability_items WHERE board_id=? ORDER BY CASE severity WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,due_date").bind(boardId).all()).results });
    if (view === 'transparency') return json({ boardId, view, data: (await db.prepare("SELECT * FROM transparency_vendor_assessments WHERE board_id=? ORDER BY CASE risk_level WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END,supplier_name").bind(boardId).all()).results });
    if (view === 'transparency_reports') return json({ boardId, view, data: (await db.prepare('SELECT id,report_year,status,row_count,payload_hash,external_status,created_by,approved_by,approved_at,created_at FROM transparency_reports WHERE board_id=? ORDER BY report_year DESC,created_at DESC').bind(boardId).all()).results });
    const [open, high, carbon, transparency] = await Promise.all([db.prepare("SELECT COUNT(*) count FROM sustainability_items WHERE board_id=? AND status NOT IN ('complete','closed')").bind(boardId).first(), db.prepare("SELECT COUNT(*) count FROM sustainability_items WHERE board_id=? AND severity='high' AND status NOT IN ('complete','closed')").bind(boardId).first(), db.prepare("SELECT COALESCE(SUM(value_numeric),0) value FROM sustainability_items WHERE board_id=? AND item_type='carbon_measurement'").bind(boardId).first(), db.prepare("SELECT COUNT(*) count,SUM(CASE WHEN status='approved' THEN 1 ELSE 0 END) approved_count,SUM(CASE WHEN risk_level IN ('high','critical') THEN 1 ELSE 0 END) high_risk_count FROM transparency_vendor_assessments WHERE board_id=?").bind(boardId).first()]);
    return json({ boardId, view, data: { open, high, carbon, transparency } });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};

export const onRequestPost: PagesFunction<Env> = async ({ env, request }) => {
  try { const v = await body(request); const boardId = String(v?.boardId || '').trim(); const action = String(v?.action || '').trim(); if (!boardId || !action) return json({ error: 'boardId_and_action_required' }, { status: 400 }); const auth = await authorizeBoardWrite(request, env, boardId); if (!auth.allowed) return json({ error: 'write_not_authorized' }, { status: 401 }); const db = requireDb(env);
    if (action === 'calculate_carbon') { const title = String(v?.title || '').trim(); const scope = String(v?.scope || '').trim(); const activity = Number(v?.activityNumeric); const factor = Number(v?.emissionFactor); const unit = String(v?.valueUnit || 'kg CO₂e').trim(); if (!title || !scopes.has(scope) || !Number.isFinite(activity) || activity < 0 || !Number.isFinite(factor) || factor < 0 || !unit || unit.length > 30) return json({ error: 'carbon_calculation_fields_invalid' }, { status: 400 }); const valueNumeric = Math.round(activity * factor * 1000) / 1000; const itemId = id('carbon'); await db.prepare("INSERT INTO sustainability_items (id,board_id,item_type,title,status,severity,scope,value_numeric,value_unit,due_date) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(itemId, boardId, 'carbon_measurement', title, 'open', v?.severity || 'medium', scope, valueNumeric, unit, v?.dueDate || null).run(); await recordAudit(db, { boardId, action: 'carbon_measurement_calculated', entityType: 'sustainability_item', entityId: itemId, userId: auth.userId || undefined, details: { scope, activityNumeric: activity, emissionFactor: factor, valueNumeric, unit, method: 'activity_x_emission_factor', reporting: 'not_configured' } }); return json({ ok: true, action, id: itemId, status: 'open', scope, activityNumeric: activity, emissionFactor: factor, valueNumeric, unit, method: 'activity_x_emission_factor', reporting: 'not_configured' }, { status: 201 }); }
    if (action === 'prepare_transparency_assessments') { const reportYear = String(v?.reportYear || '').trim(); if (!validYear(reportYear)) return json({ error: 'report_year_required' }, { status: 400 }); const rows = (await db.prepare("SELECT supplier_name supplierName,COUNT(*) sourceCount FROM supplier_invoices WHERE board_id=? GROUP BY supplier_name UNION SELECT supplier_name supplierName,COUNT(*) sourceCount FROM purchase_orders WHERE board_id=? GROUP BY supplier_name UNION SELECT counterparty supplierName,COUNT(*) sourceCount FROM contracts WHERE board_id=? AND contract_type='supplier' AND counterparty IS NOT NULL GROUP BY counterparty").bind(boardId, boardId, boardId).all()).results as Record<string, unknown>[]; const names = new Map<string, number>(); for (const row of rows) { const name = String(row.supplierName || '').trim(); if (name) names.set(name, (names.get(name) || 0) + Number(row.sourceCount || 0)); } if (!names.size) return json({ error: 'supplier_sources_empty' }, { status: 409 }); for (const [supplierName, sourceCount] of names) await db.prepare("INSERT INTO transparency_vendor_assessments (id,board_id,supplier_name,report_year,status,risk_level,source_count,assessment_notes,created_by) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(board_id,supplier_name,report_year) DO UPDATE SET source_count=excluded.source_count").bind(id('vendorassess'), boardId, supplierName, reportYear, 'prepared', 'medium', sourceCount, 'Kildegrunnlag fra innkjøp, leverandørfakturaer og kontrakter. Faglig vurdering mangler.', auth.userId || 'api').run(); await recordAudit(db, { boardId, action: 'transparency_assessments_prepared', entityType: 'transparency_vendor_assessment', entityId: reportYear, userId: auth.userId || undefined, details: { reportYear, rowCount: names.size, screening: 'not_configured', publication: 'not_configured' } }); return json({ ok: true, action, reportYear, rowCount: names.size, status: 'prepared', screening: 'not_configured', publication: 'not_configured', requiresHumanReview: true }, { status: 201 }); }
    if (action === 'review_transparency_assessment') { const assessmentId = String(v?.assessmentId || '').trim(); const riskLevel = String(v?.riskLevel || 'medium').trim(); if (!assessmentId || !riskLevels.has(riskLevel)) return json({ error: 'assessment_and_risk_required' }, { status: 400 }); const result = await db.prepare("UPDATE transparency_vendor_assessments SET status='review',risk_level=?,assessment_notes=?,evidence_ref=? WHERE id=? AND board_id=? AND status IN ('prepared','review')").bind(riskLevel, String(v?.assessmentNotes || '').trim() || null, String(v?.evidenceRef || '').trim() || null, assessmentId, boardId).run(); if (!result.meta?.changes) return json({ error: 'assessment_not_open_or_found' }, { status: 409 }); await recordAudit(db, { boardId, action: 'transparency_assessment_reviewed', entityType: 'transparency_vendor_assessment', entityId: assessmentId, userId: auth.userId || undefined, details: { riskLevel } }); return json({ ok: true, action, assessmentId, status: 'review', riskLevel, requiresHumanApproval: true }); }
    if (action === 'approve_transparency_assessment') { const assessmentId = String(v?.assessmentId || '').trim(); if (!assessmentId) return json({ error: 'assessmentId_required' }, { status: 400 }); const result = await db.prepare("UPDATE transparency_vendor_assessments SET status='approved',reviewed_by=?,reviewed_at=datetime('now') WHERE id=? AND board_id=? AND status IN ('prepared','review')").bind(auth.userId || 'api', assessmentId, boardId).run(); if (!result.meta?.changes) return json({ error: 'assessment_not_open_or_found' }, { status: 409 }); await recordAudit(db, { boardId, action: 'transparency_assessment_approved', entityType: 'transparency_vendor_assessment', entityId: assessmentId, userId: auth.userId || undefined, details: { screening: 'not_configured' } }); return json({ ok: true, action, assessmentId, status: 'approved', screening: 'not_configured' }); }
    if (action === 'prepare_transparency_report') { const reportYear = String(v?.reportYear || '').trim(); if (!validYear(reportYear)) return json({ error: 'report_year_required' }, { status: 400 }); const rows = (await db.prepare("SELECT id,supplier_name,report_year,risk_level,status,source_count,assessment_notes,evidence_ref FROM transparency_vendor_assessments WHERE board_id=? AND report_year=? ORDER BY supplier_name,id").bind(boardId, reportYear).all()).results as Record<string, unknown>[]; if (!rows.length) return json({ error: 'transparency_assessments_empty' }, { status: 409 }); const payload = JSON.stringify({ schemaVersion: 'styr-transparency-1', reportYear, boardId, assessmentCount: rows.length, assessments: rows }); const payloadHash = await sha256(payload); const reportId = id('transparencyreport'); try { await db.prepare("INSERT INTO transparency_reports (id,board_id,report_year,status,row_count,payload_hash,payload,external_status,created_by) VALUES (?,?,?,'prepared',?,?,?,'not_configured',?)").bind(reportId, boardId, reportYear, rows.length, payloadHash, payload, auth.userId || 'api').run(); } catch (error) { if (error instanceof Error && error.message.includes('UNIQUE')) return json({ error: 'open_transparency_report_exists' }, { status: 409 }); throw error; } await recordAudit(db, { boardId, action: 'transparency_report_prepared', entityType: 'transparency_report', entityId: reportId, userId: auth.userId || undefined, details: { reportYear, rowCount: rows.length, payloadHash, publication: 'not_configured' } }); return json({ ok: true, action, reportId, reportYear, status: 'prepared', rowCount: rows.length, payloadHash, publication: 'not_configured', requiresHumanReview: true }, { status: 201 }); }
    if (action === 'approve_transparency_report') { const reportId = String(v?.reportId || '').trim(); if (!reportId) return json({ error: 'reportId_required' }, { status: 400 }); const result = await db.prepare("UPDATE transparency_reports SET status='approved',approved_by=?,approved_at=datetime('now') WHERE id=? AND board_id=? AND status IN ('prepared','review')").bind(auth.userId || 'api', reportId, boardId).run(); if (!result.meta?.changes) return json({ error: 'report_not_open_or_found' }, { status: 409 }); await recordAudit(db, { boardId, action: 'transparency_report_approved', entityType: 'transparency_report', entityId: reportId, userId: auth.userId || undefined, details: { publication: 'not_configured', requiresHumanPublication: true } }); return json({ ok: true, action, reportId, status: 'approved', publication: 'not_configured', requiresHumanPublication: true }); }
    if (action === 'create_item') { const title = String(v?.title || '').trim(); if (!title) return json({ error: 'title_required' }, { status: 400 }); const itemId = id('sustain'); await db.prepare("INSERT INTO sustainability_items (id,board_id,item_type,title,status,severity,scope,value_numeric,value_unit,due_date) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(itemId, boardId, String(v?.itemType || 'hms_incident'), title, 'open', v?.severity || 'medium', v?.scope || null, v?.valueNumeric ?? null, v?.valueUnit || null, v?.dueDate || null).run(); await recordAudit(db, { boardId, action: 'sustainability_item_created', entityType: 'sustainability_item', entityId: itemId, userId: auth.userId || undefined, details: { itemType: String(v?.itemType || 'hms_incident'), severity: String(v?.severity || 'medium') } }); return json({ ok: true, id: itemId, status: 'open' }, { status: 201 }); }
    if (action === 'close_item') { const itemId = String(v?.itemId || '').trim(); if (!itemId) return json({ error: 'itemId_required' }, { status: 400 }); const result = await db.prepare("UPDATE sustainability_items SET status='complete',updated_at=datetime('now') WHERE id=? AND board_id=? AND status NOT IN ('complete','closed')").bind(itemId, boardId).run(); if (!result.meta?.changes) return json({ error: 'item_not_open_or_found' }, { status: 409 }); await recordAudit(db, { boardId, action: 'sustainability_item_closed', entityType: 'sustainability_item', entityId: itemId, userId: auth.userId || undefined }); return json({ ok: true, id: itemId, status: 'complete' }); }
    return json({ error: 'unknown_action', allowed: ['calculate_carbon', 'prepare_transparency_assessments', 'review_transparency_assessment', 'approve_transparency_assessment', 'prepare_transparency_report', 'approve_transparency_report', 'create_item', 'close_item'] }, { status: 400 });
  } catch (error) { return json({ error: 'database_unavailable', detail: error instanceof Error ? error.message : 'unknown' }, { status: 503 }); }
};
